/**
 * NihongoGo — Achievement seed data (24 huy hiệu).
 * metric dùng đúng union AchievementMetric trong types.ts.
 * icon = tên icon Lucide; xpReward trong khoảng 5–100.
 */
import type { SeedAchievement } from './types'

export const achievements: SeedAchievement[] = [
  {
    code: 'FIRST_STEP',
    title: 'Bước Chân Đầu Tiên',
    description: 'Hoàn thành bài học đầu tiên của bạn trên hành trình chinh phục tiếng Nhật.',
    icon: 'Footprints',
    tier: 'BRONZE',
    category: 'LESSON',
    metric: 'LESSONS_COMPLETED',
    threshold: 1,
    xpReward: 10,
  },
  {
    code: 'LESSON_5',
    title: 'Học Miệt Mài',
    description: 'Hoàn thành 5 bài học — khởi đầu thật vững chắc!',
    icon: 'BookOpen',
    tier: 'SILVER',
    category: 'LESSON',
    metric: 'LESSONS_COMPLETED',
    threshold: 5,
    xpReward: 20,
  },
  {
    code: 'LESSON_10',
    title: 'Chặng 10 Bài Học',
    description: 'Hoàn thành 10 bài học — quyết tâm đáng nể!',
    icon: 'GraduationCap',
    tier: 'GOLD',
    category: 'LESSON',
    metric: 'LESSONS_COMPLETED',
    threshold: 10,
    xpReward: 40,
  },
  {
    code: 'LESSON_25',
    title: 'Chiến Binh Học Tập',
    description: 'Hoàn thành 25 bài học. Không gì có thể cản bước bạn!',
    icon: 'Crown',
    tier: 'DIAMOND',
    category: 'LESSON',
    metric: 'LESSONS_COMPLETED',
    threshold: 25,
    xpReward: 80,
  },
  {
    code: 'STREAK_3',
    title: 'Nhóm Lửa Đam Mê',
    description: 'Duy trì chuỗi học 3 ngày liên tiếp — ngọn lửa đã được nhóm lên.',
    icon: 'Flame',
    tier: 'BRONZE',
    category: 'STREAK',
    metric: 'CURRENT_STREAK',
    threshold: 3,
    xpReward: 10,
  },
  {
    code: 'STREAK_7',
    title: 'Trọn Một Tuần',
    description: 'Học đều đặn 7 ngày liên tiếp — trọn vẹn một tuần không bỏ cuộc!',
    icon: 'Flame',
    tier: 'SILVER',
    category: 'STREAK',
    metric: 'CURRENT_STREAK',
    threshold: 7,
    xpReward: 25,
  },
  {
    code: 'STREAK_30',
    title: 'Ngọn Lửa 30 Ngày',
    description: 'Chuỗi học 30 ngày liên tiếp — bạn là hiện thân của sự kiên trì!',
    icon: 'Flame',
    tier: 'GOLD',
    category: 'STREAK',
    metric: 'CURRENT_STREAK',
    threshold: 30,
    xpReward: 60,
  },
  {
    code: 'XP_100',
    title: 'Khởi Động XP',
    description: 'Đạt tổng cộng 100 XP. Mỗi điểm XP là một bước tiến nhỏ.',
    icon: 'Zap',
    tier: 'BRONZE',
    category: 'XP',
    metric: 'TOTAL_XP',
    threshold: 100,
    xpReward: 5,
  },
  {
    code: 'XP_1000',
    title: 'Nghìn Điểm Vinh Quang',
    description: 'Đạt tổng cộng 1.000 XP — bạn đang bứt phá thật sự!',
    icon: 'Zap',
    tier: 'SILVER',
    category: 'XP',
    metric: 'TOTAL_XP',
    threshold: 1000,
    xpReward: 25,
  },
  {
    code: 'XP_5000',
    title: 'Ngũ Thiên Điểm',
    description: 'Đạt tổng cộng 5.000 XP — năng lực tích lũy thật ấn tượng!',
    icon: 'Sparkles',
    tier: 'GOLD',
    category: 'XP',
    metric: 'TOTAL_XP',
    threshold: 5000,
    xpReward: 50,
  },
  {
    code: 'XP_10000',
    title: 'Huyền Thoại XP',
    description: 'Đạt tổng cộng 10.000 XP — đỉnh cao mà ít người chạm tới!',
    icon: 'Trophy',
    tier: 'DIAMOND',
    category: 'XP',
    metric: 'TOTAL_XP',
    threshold: 10000,
    xpReward: 100,
  },
  {
    code: 'PERFECT_1',
    title: 'Mở Màn Hoàn Hảo',
    description: 'Hoàn hảo 1 bài học: không sai một câu nào. Quá đỉnh!',
    icon: 'Star',
    tier: 'BRONZE',
    category: 'LESSON',
    metric: 'PERFECT_LESSONS',
    threshold: 1,
    xpReward: 15,
  },
  {
    code: 'PERFECT_10',
    title: 'Thợ Săn Điểm Tuyệt Đối',
    description: 'Hoàn hảo 10 bài học — độ chính xác như máy móc!',
    icon: 'Star',
    tier: 'SILVER',
    category: 'LESSON',
    metric: 'PERFECT_LESSONS',
    threshold: 10,
    xpReward: 35,
  },
  {
    code: 'KANA_10',
    title: 'Vỡ Lòng Kana',
    description: 'Làm chủ 10 ký tự kana — bảng chữ cái đang dần thuộc về bạn.',
    icon: 'Languages',
    tier: 'BRONZE',
    category: 'KANA',
    metric: 'KANA_MASTERED',
    threshold: 10,
    xpReward: 10,
  },
  {
    code: 'KANA_46',
    title: 'Thuộc Lòng 46 Kana',
    description: 'Làm chủ 46 ký tự kana — trọn bộ kana cơ bản đã nằm trong tay.',
    icon: 'Languages',
    tier: 'SILVER',
    category: 'KANA',
    metric: 'KANA_MASTERED',
    threshold: 46,
    xpReward: 25,
  },
  {
    code: 'KANA_104',
    title: 'Song Toàn Kana',
    description: 'Làm chủ 104 ký tự kana — toàn bộ hiragana và katakana, xuất sắc!',
    icon: 'Languages',
    tier: 'GOLD',
    category: 'KANA',
    metric: 'KANA_MASTERED',
    threshold: 104,
    xpReward: 60,
  },
  {
    code: 'KANJI_5',
    title: 'Nhập Môn Kanji',
    description: 'Làm chủ 5 chữ kanji đầu tiên — những viên gạch đầu của tòa lâu đài.',
    icon: 'PenLine',
    tier: 'BRONZE',
    category: 'KANJI',
    metric: 'KANJI_MASTERED',
    threshold: 5,
    xpReward: 10,
  },
  {
    code: 'KANJI_20',
    title: 'Bút Pháp Lưu Luyến',
    description: 'Làm chủ 20 chữ kanji — mỗi nét chữ giờ đều kể chuyện với bạn.',
    icon: 'PenLine',
    tier: 'SILVER',
    category: 'KANJI',
    metric: 'KANJI_MASTERED',
    threshold: 20,
    xpReward: 30,
  },
  {
    code: 'VOCAB_50',
    title: 'Kho Từ Khởi Đầu',
    description: 'Làm chủ 50 từ vựng — hành trang khởi đầu đã sẵn sàng.',
    icon: 'BookOpen',
    tier: 'BRONZE',
    category: 'SKILL',
    metric: 'VOCAB_MASTERED',
    threshold: 50,
    xpReward: 15,
  },
  {
    code: 'VOCAB_200',
    title: 'Nhà Sưu Tầm Từ Vựng',
    description: 'Làm chủ 200 từ vựng — giao tiếp mỗi ngày tự tin hẳn!',
    icon: 'BookOpen',
    tier: 'SILVER',
    category: 'SKILL',
    metric: 'VOCAB_MASTERED',
    threshold: 200,
    xpReward: 40,
  },
  {
    code: 'LISTENING_10',
    title: 'Tai Thính Nhật Ngữ',
    description: 'Hoàn thành 10 bài luyện nghe — đôi tai ngày càng "Nhật" hơn.',
    icon: 'Ear',
    tier: 'SILVER',
    category: 'SKILL',
    metric: 'LISTENING_NODES',
    threshold: 10,
    xpReward: 25,
  },
  {
    code: 'SPEAKING_10',
    title: 'Giọng Nói Tự Tin',
    description: 'Hoàn thành 10 bài luyện nói — mạnh dạn mở miệng là thắng nửa chặng đường!',
    icon: 'Mic',
    tier: 'SILVER',
    category: 'SKILL',
    metric: 'SPEAKING_NODES',
    threshold: 10,
    xpReward: 25,
  },
  {
    code: 'MISTAKE_FIXER',
    title: 'Thợ Sửa Lỗi',
    description: 'Khắc phục thành công 10 lỗi đã mắc — biết sai mà sửa mới là giỏi!',
    icon: 'Wrench',
    tier: 'BRONZE',
    category: 'MISC',
    metric: 'MISTAKES_RESOLVED',
    threshold: 10,
    xpReward: 20,
  },
  {
    code: 'QUEST_MASTER',
    title: 'Bậc Thầy Nhiệm Vụ',
    description: 'Hoàn thành 10 nhiệm vụ — thói quen tốt mỗi ngày đang được đắp xây.',
    icon: 'Target',
    tier: 'SILVER',
    category: 'MISC',
    metric: 'QUESTS_COMPLETED',
    threshold: 10,
    xpReward: 30,
  },
]
