/**
 * NihongoGo — Kana seed data (gojūon hoàn chỉnh).
 * 208 ký tự = 104 hiragana + 104 katakana.
 * Mỗi script: 46 BASIC + 20 DAKUTEN + 5 HANDAKUTEN + 33 YOUON.
 * row: hàng gojūon (あ/ア=1 … ん/ン=11); dakuten/handakuten/youon dùng row của ký tự gốc.
 * strokeCount: bảng chuẩn; DAKUTEN = base+2, HANDAKUTEN = base+1, YOUON = base+2 (base = ký tự nền, tính cả dakuten nếu có).
 * Toàn bộ exampleWord là từ tiếng Nhật thật thông dụng, thuần kana → exampleReading trùng exampleWord.
 */
import type { SeedKanaCharacter } from './types'

type KanaGroup = SeedKanaCharacter['group']

function hiragana(
  character: string,
  romaji: string,
  row: number,
  strokeCount: number,
  group: KanaGroup,
  exampleWord: string,
  exampleMeaning: string,
): SeedKanaCharacter {
  return {
    character,
    romaji,
    type: 'HIRAGANA',
    group,
    row,
    strokeCount,
    exampleWord,
    exampleReading: exampleWord,
    exampleMeaning,
  }
}

function katakana(
  character: string,
  romaji: string,
  row: number,
  strokeCount: number,
  group: KanaGroup,
  exampleWord: string,
  exampleMeaning: string,
): SeedKanaCharacter {
  return {
    character,
    romaji,
    type: 'KATAKANA',
    group,
    row,
    strokeCount,
    exampleWord,
    exampleReading: exampleWord,
    exampleMeaning,
  }
}

export const kanaCharacters: SeedKanaCharacter[] = [
  /* ============ HIRAGANA — BASIC (46) ============ */
  hiragana('あ', 'a', 1, 3, 'BASIC', 'あめ', 'mưa'),
  hiragana('い', 'i', 1, 2, 'BASIC', 'いぬ', 'con chó'),
  hiragana('う', 'u', 1, 2, 'BASIC', 'うみ', 'biển'),
  hiragana('え', 'e', 1, 2, 'BASIC', 'えき', 'nhà ga'),
  hiragana('お', 'o', 1, 3, 'BASIC', 'おかし', 'bánh kẹo'),
  hiragana('か', 'ka', 2, 2, 'BASIC', 'かさ', 'cây dù'),
  hiragana('き', 'ki', 2, 3, 'BASIC', 'きのこ', 'cây nấm'),
  hiragana('く', 'ku', 2, 1, 'BASIC', 'くつ', 'đôi giày'),
  hiragana('け', 'ke', 2, 3, 'BASIC', 'わけ', 'lý do'),
  hiragana('こ', 'ko', 2, 2, 'BASIC', 'こども', 'trẻ em'),
  hiragana('さ', 'sa', 3, 3, 'BASIC', 'さかな', 'con cá'),
  hiragana('し', 'shi', 3, 1, 'BASIC', 'しお', 'muối'),
  hiragana('す', 'su', 3, 2, 'BASIC', 'すし', 'món sushi'),
  hiragana('せ', 'se', 3, 3, 'BASIC', 'せかい', 'thế giới'),
  hiragana('そ', 'so', 3, 1, 'BASIC', 'そら', 'bầu trời'),
  hiragana('た', 'ta', 4, 4, 'BASIC', 'たまご', 'quả trứng'),
  hiragana('ち', 'chi', 4, 2, 'BASIC', 'おちゃ', 'trà'),
  hiragana('つ', 'tsu', 4, 1, 'BASIC', 'つき', 'mặt trăng'),
  hiragana('て', 'te', 4, 1, 'BASIC', 'て', 'bàn tay'),
  hiragana('と', 'to', 4, 2, 'BASIC', 'とり', 'con chim'),
  hiragana('な', 'na', 5, 4, 'BASIC', 'なつ', 'mùa hè'),
  hiragana('に', 'ni', 5, 3, 'BASIC', 'にく', 'thịt'),
  hiragana('ぬ', 'nu', 5, 2, 'BASIC', 'ぬの', 'tấm vải'),
  hiragana('ね', 'ne', 5, 2, 'BASIC', 'ねこ', 'con mèo'),
  hiragana('の', 'no', 5, 1, 'BASIC', 'のり', 'rong biển'),
  hiragana('は', 'ha', 6, 3, 'BASIC', 'はな', 'bông hoa'),
  hiragana('ひ', 'hi', 6, 1, 'BASIC', 'ひかり', 'ánh sáng'),
  hiragana('ふ', 'fu', 6, 4, 'BASIC', 'ふね', 'con thuyền'),
  hiragana('へ', 'he', 6, 1, 'BASIC', 'へや', 'căn phòng'),
  hiragana('ほ', 'ho', 6, 4, 'BASIC', 'ほし', 'ngôi sao'),
  hiragana('ま', 'ma', 7, 3, 'BASIC', 'まど', 'cửa sổ'),
  hiragana('み', 'mi', 7, 2, 'BASIC', 'みず', 'nước'),
  hiragana('む', 'mu', 7, 3, 'BASIC', 'むし', 'con côn trùng'),
  hiragana('め', 'me', 7, 2, 'BASIC', 'めがね', 'cái kính (đeo mắt)'),
  hiragana('も', 'mo', 7, 3, 'BASIC', 'もの', 'vật, đồ vật'),
  hiragana('や', 'ya', 8, 3, 'BASIC', 'やま', 'ngọn núi'),
  hiragana('ゆ', 'yu', 8, 2, 'BASIC', 'ゆき', 'tuyết'),
  hiragana('よ', 'yo', 8, 2, 'BASIC', 'よる', 'ban đêm'),
  hiragana('ら', 'ra', 9, 2, 'BASIC', 'さくら', 'hoa anh đào'),
  hiragana('り', 'ri', 9, 2, 'BASIC', 'りんご', 'quả táo'),
  hiragana('る', 'ru', 9, 1, 'BASIC', 'くるま', 'xe hơi'),
  hiragana('れ', 're', 9, 2, 'BASIC', 'きれい', 'xinh đẹp'),
  hiragana('ろ', 'ro', 9, 1, 'BASIC', 'いろ', 'màu sắc'),
  hiragana('わ', 'wa', 10, 2, 'BASIC', 'わたし', 'tôi'),
  hiragana('を', 'wo', 10, 3, 'BASIC', 'ほんをよむ', 'đọc sách'),
  hiragana('ん', 'n', 11, 1, 'BASIC', 'ほん', 'quyển sách'),

  /* ============ HIRAGANA — DAKUTEN (20) ============ */
  hiragana('が', 'ga', 2, 4, 'DAKUTEN', 'がっこう', 'trường học'),
  hiragana('ぎ', 'gi', 2, 5, 'DAKUTEN', 'ぎんこう', 'ngân hàng'),
  hiragana('ぐ', 'gu', 2, 3, 'DAKUTEN', 'いく', 'đi'),
  hiragana('げ', 'ge', 2, 5, 'DAKUTEN', 'げんき', 'khỏe mạnh, tràn năng lượng'),
  hiragana('ご', 'go', 2, 4, 'DAKUTEN', 'ごはん', 'cơm'),
  hiragana('ざ', 'za', 3, 5, 'DAKUTEN', 'ざっし', 'tạp chí'),
  hiragana('じ', 'ji', 3, 3, 'DAKUTEN', 'じかん', 'thời gian'),
  hiragana('ず', 'zu', 3, 4, 'DAKUTEN', 'ずっと', 'luôn luôn'),
  hiragana('ぜ', 'ze', 3, 5, 'DAKUTEN', 'ぜんぶ', 'tất cả'),
  hiragana('ぞ', 'zo', 3, 3, 'DAKUTEN', 'ぞう', 'con voi'),
  hiragana('だ', 'da', 4, 6, 'DAKUTEN', 'だれ', 'ai'),
  hiragana('ぢ', 'ji', 4, 4, 'DAKUTEN', 'はなぢ', 'chảy máu cam'),
  hiragana('づ', 'zu', 4, 3, 'DAKUTEN', 'つづく', 'tiếp tục'),
  hiragana('で', 'de', 4, 3, 'DAKUTEN', 'でんわ', 'điện thoại'),
  hiragana('ど', 'do', 4, 4, 'DAKUTEN', 'どうぶつ', 'con vật'),
  hiragana('ば', 'ba', 6, 5, 'DAKUTEN', 'ばんごはん', 'bữa tối'),
  hiragana('び', 'bi', 6, 3, 'DAKUTEN', 'くちびる', 'đôi môi'),
  hiragana('ぶ', 'bu', 6, 6, 'DAKUTEN', 'ぶどう', 'quả nho'),
  hiragana('べ', 'be', 6, 3, 'DAKUTEN', 'たべる', 'ăn'),
  hiragana('ぼ', 'bo', 6, 6, 'DAKUTEN', 'ぼうし', 'cái mũ'),

  /* ============ HIRAGANA — HANDAKUTEN (5) ============ */
  hiragana('ぱ', 'pa', 6, 4, 'HANDAKUTEN', 'ぱん', 'bánh mì'),
  hiragana('ぴ', 'pi', 6, 2, 'HANDAKUTEN', 'ぴかぴか', 'sáng lấp lánh'),
  hiragana('ぷ', 'pu', 6, 5, 'HANDAKUTEN', 'ぷんぷん', 'tức giận hầm hầm'),
  hiragana('ぺ', 'pe', 6, 2, 'HANDAKUTEN', 'ぺこぺこ', 'đói meo sét'),
  hiragana('ぽ', 'po', 6, 5, 'HANDAKUTEN', 'ぽかぽか', 'ấm áp dễ chịu'),

  /* ============ HIRAGANA — YOUON (33) ============ */
  hiragana('きゃ', 'kya', 2, 5, 'YOUON', 'きゃく', 'khách'),
  hiragana('きゅ', 'kyu', 2, 5, 'YOUON', 'きゅうり', 'quả dưa chuột'),
  hiragana('きょ', 'kyo', 2, 5, 'YOUON', 'きょう', 'hôm nay'),
  hiragana('しゃ', 'sha', 3, 3, 'YOUON', 'しゃしん', 'bức ảnh'),
  hiragana('しゅ', 'shu', 3, 3, 'YOUON', 'しゅみ', 'sở thích'),
  hiragana('しょ', 'sho', 3, 3, 'YOUON', 'しょくじ', 'bữa ăn'),
  hiragana('ちゃ', 'cha', 4, 4, 'YOUON', 'ちゃいろ', 'màu nâu'),
  hiragana('ちゅ', 'chu', 4, 4, 'YOUON', 'ちゅうい', 'sự chú ý'),
  hiragana('ちょ', 'cho', 4, 4, 'YOUON', 'ちょっと', 'một chút'),
  hiragana('にゃ', 'nya', 5, 5, 'YOUON', 'こんにゃく', 'thạch konnyaku'),
  hiragana('にゅ', 'nyu', 5, 5, 'YOUON', 'にゅうがく', 'sự nhập học'),
  hiragana('にょ', 'nyo', 5, 5, 'YOUON', 'にょらい', 'Đức Như Lai'),
  hiragana('ひゃ', 'hya', 6, 3, 'YOUON', 'ひゃく', 'một trăm'),
  hiragana('ひゅ', 'hyu', 6, 3, 'YOUON', 'ひゅうひゅう', 'tiếng gió rít'),
  hiragana('ひょ', 'hyo', 6, 3, 'YOUON', 'ひょう', 'mưa đá'),
  hiragana('みゃ', 'mya', 7, 4, 'YOUON', 'みゃく', 'mạch (đập)'),
  hiragana('みゅ', 'myu', 7, 4, 'YOUON', 'みゅう', 'tiếng mèo kêu meo meo'),
  hiragana('みょ', 'myo', 7, 4, 'YOUON', 'みょうじ', 'họ (tên họ)'),
  hiragana('りゃ', 'rya', 9, 4, 'YOUON', 'たいりゃく', 'tóm tắt, đại lược'),
  hiragana('りゅ', 'ryu', 9, 4, 'YOUON', 'りゅう', 'con rồng'),
  hiragana('りょ', 'ryo', 9, 4, 'YOUON', 'りょこう', 'chuyến du lịch'),
  hiragana('ぎゃ', 'gya', 2, 7, 'YOUON', 'ぎゃく', 'sự ngược lại'),
  hiragana('ぎゅ', 'gyu', 2, 7, 'YOUON', 'ぎゅうにく', 'thịt bò'),
  hiragana('ぎょ', 'gyo', 2, 7, 'YOUON', 'ぎょうざ', 'bánh xếp gyōza'),
  hiragana('じゃ', 'ja', 3, 5, 'YOUON', 'じゃあ', 'vậy thì'),
  hiragana('じゅ', 'ju', 3, 5, 'YOUON', 'じゅぎょう', 'buổi học'),
  hiragana('じょ', 'jo', 3, 5, 'YOUON', 'じょうず', 'khéo léo'),
  hiragana('びゃ', 'bya', 6, 5, 'YOUON', 'さんびゃく', 'ba trăm'),
  hiragana('びゅ', 'byu', 6, 5, 'YOUON', 'びょういん', 'bệnh viện'),
  hiragana('びょ', 'byo', 6, 5, 'YOUON', 'びょうき', 'bệnh tật'),
  hiragana('ぴゃ', 'pya', 6, 4, 'YOUON', 'はっぴゃく', 'tám trăm'),
  hiragana('ぴゅ', 'pyu', 6, 4, 'YOUON', 'ぴゅうぴゅう', 'tiếng gió viu viu'),
  hiragana('ぴょ', 'pyo', 6, 4, 'YOUON', 'ぴょんぴょん', 'nhảy tưng tưng'),

  /* ============ KATAKANA — BASIC (46) ============ */
  katakana('ア', 'a', 1, 2, 'BASIC', 'アメリカ', 'nước Mỹ'),
  katakana('イ', 'i', 1, 2, 'BASIC', 'イタリア', 'nước Ý'),
  katakana('ウ', 'u', 1, 3, 'BASIC', 'ウイルス', 'vi-rút'),
  katakana('エ', 'e', 1, 3, 'BASIC', 'エアコン', 'máy điều hòa'),
  katakana('オ', 'o', 1, 3, 'BASIC', 'オレンジ', 'quả cam'),
  katakana('カ', 'ka', 2, 2, 'BASIC', 'カメラ', 'máy ảnh'),
  katakana('キ', 'ki', 2, 3, 'BASIC', 'キムチ', 'món kim chi'),
  katakana('ク', 'ku', 2, 2, 'BASIC', 'クラス', 'lớp học'),
  katakana('ケ', 'ke', 2, 3, 'BASIC', 'ケーキ', 'bánh ngọt'),
  katakana('コ', 'ko', 2, 2, 'BASIC', 'コーヒー', 'cà phê'),
  katakana('サ', 'sa', 3, 3, 'BASIC', 'サッカー', 'bóng đá'),
  katakana('シ', 'shi', 3, 3, 'BASIC', 'シール', 'tem dán'),
  katakana('ス', 'su', 3, 2, 'BASIC', 'スープ', 'món súp'),
  katakana('セ', 'se', 3, 2, 'BASIC', 'セーター', 'áo len'),
  katakana('ソ', 'so', 3, 2, 'BASIC', 'ソファ', 'ghế sofa'),
  katakana('タ', 'ta', 4, 3, 'BASIC', 'タクシー', 'xe tắc xi'),
  katakana('チ', 'chi', 4, 3, 'BASIC', 'チーズ', 'phô mai'),
  katakana('ツ', 'tsu', 4, 3, 'BASIC', 'ツアー', 'chuyến tham quan'),
  katakana('テ', 'te', 4, 3, 'BASIC', 'テレビ', 'tivi'),
  katakana('ト', 'to', 4, 2, 'BASIC', 'トマト', 'cà chua'),
  katakana('ナ', 'na', 5, 4, 'BASIC', 'バナナ', 'quả chuối'),
  katakana('ニ', 'ni', 5, 2, 'BASIC', 'ニット', 'đồ len đan'),
  katakana('ヌ', 'nu', 5, 2, 'BASIC', 'ヌードル', 'mì sợi'),
  katakana('ネ', 'ne', 5, 4, 'BASIC', 'ネコ', 'con mèo'),
  katakana('ノ', 'no', 5, 1, 'BASIC', 'ノート', 'vở ghi chép'),
  katakana('ハ', 'ha', 6, 2, 'BASIC', 'ハンカチ', 'khăn tay'),
  katakana('ヒ', 'hi', 6, 2, 'BASIC', 'ヒーター', 'máy sưởi'),
  katakana('フ', 'fu', 6, 1, 'BASIC', 'フライパン', 'chảo rán'),
  katakana('ヘ', 'he', 6, 2, 'BASIC', 'ヘリコプター', 'máy bay trực thăng'),
  katakana('ホ', 'ho', 6, 4, 'BASIC', 'ホテル', 'khách sạn'),
  katakana('マ', 'ma', 7, 2, 'BASIC', 'マンゴー', 'quả xoài'),
  katakana('ミ', 'mi', 7, 3, 'BASIC', 'ミルク', 'sữa'),
  katakana('ム', 'mu', 7, 2, 'BASIC', 'ムード', 'không khí, tâm trạng'),
  katakana('メ', 'me', 7, 2, 'BASIC', 'メール', 'thư điện tử'),
  katakana('モ', 'mo', 7, 3, 'BASIC', 'モデル', 'người mẫu'),
  katakana('ヤ', 'ya', 8, 2, 'BASIC', 'タイヤ', 'lốp xe'),
  katakana('ユ', 'yu', 8, 2, 'BASIC', 'ユニフォーム', 'đồng phục'),
  katakana('ヨ', 'yo', 8, 3, 'BASIC', 'ヨーグルト', 'sữa chua'),
  katakana('ラ', 'ra', 9, 2, 'BASIC', 'ラーメン', 'mì ramen'),
  katakana('リ', 'ri', 9, 2, 'BASIC', 'リボン', 'cái nơ'),
  katakana('ル', 'ru', 9, 2, 'BASIC', 'ルール', 'quy tắc'),
  katakana('レ', 're', 9, 1, 'BASIC', 'レモン', 'quả chanh'),
  katakana('ロ', 'ro', 9, 3, 'BASIC', 'ロボット', 'rô-bốt'),
  katakana('ワ', 'wa', 10, 2, 'BASIC', 'ワイン', 'rượu vang'),
  katakana('ヲ', 'wo', 10, 3, 'BASIC', 'ホンヲヨム', 'đọc sách (dạng cổ của を)'),
  katakana('ン', 'n', 11, 2, 'BASIC', 'ペン', 'cây bút'),

  /* ============ KATAKANA — DAKUTEN (20) ============ */
  katakana('ガ', 'ga', 2, 4, 'DAKUTEN', 'ガム', 'kẹo cao su'),
  katakana('ギ', 'gi', 2, 5, 'DAKUTEN', 'ギター', 'đàn ghi-ta'),
  katakana('グ', 'gu', 2, 4, 'DAKUTEN', 'グラス', 'cái cốc'),
  katakana('ゲ', 'ge', 2, 5, 'DAKUTEN', 'ゲーム', 'trò chơi'),
  katakana('ゴ', 'go', 2, 4, 'DAKUTEN', 'ゴリラ', 'con khỉ đột'),
  katakana('ザ', 'za', 3, 5, 'DAKUTEN', 'ピザ', 'bánh pizza'),
  katakana('ジ', 'ji', 3, 5, 'DAKUTEN', 'ラジオ', 'đài phát thanh'),
  katakana('ズ', 'zu', 3, 4, 'DAKUTEN', 'ズボン', 'quần dài'),
  katakana('ゼ', 'ze', 3, 4, 'DAKUTEN', 'ゼロ', 'số không'),
  katakana('ゾ', 'zo', 3, 4, 'DAKUTEN', 'ゾウ', 'con voi'),
  katakana('ダ', 'da', 4, 5, 'DAKUTEN', 'ダンス', 'điệu múa'),
  katakana('ヂ', 'ji', 4, 5, 'DAKUTEN', 'ブリヂストン', 'hãng Bridgestone'),
  katakana('ヅ', 'zu', 4, 5, 'DAKUTEN', 'ミカヅキ', 'trăng lưỡi liềm'),
  katakana('デ', 'de', 4, 5, 'DAKUTEN', 'デパート', 'bách hóa tổng hợp'),
  katakana('ド', 'do', 4, 4, 'DAKUTEN', 'ドア', 'cánh cửa'),
  katakana('バ', 'ba', 6, 4, 'DAKUTEN', 'バス', 'xe buýt'),
  katakana('ビ', 'bi', 6, 4, 'DAKUTEN', 'ビール', 'bia'),
  katakana('ブ', 'bu', 6, 3, 'DAKUTEN', 'テーブル', 'cái bàn'),
  katakana('ベ', 'be', 6, 4, 'DAKUTEN', 'ベッド', 'cái giường'),
  katakana('ボ', 'bo', 6, 6, 'DAKUTEN', 'ボール', 'quả bóng'),

  /* ============ KATAKANA — HANDAKUTEN (5) ============ */
  katakana('パ', 'pa', 6, 3, 'HANDAKUTEN', 'パン', 'bánh mì'),
  katakana('ピ', 'pi', 6, 3, 'HANDAKUTEN', 'ピアノ', 'đàn piano'),
  katakana('プ', 'pu', 6, 2, 'HANDAKUTEN', 'プール', 'bể bơi'),
  katakana('ペ', 'pe', 6, 3, 'HANDAKUTEN', 'ペンギン', 'chim cánh cụt'),
  katakana('ポ', 'po', 6, 5, 'HANDAKUTEN', 'ポスト', 'hộp thư'),

  /* ============ KATAKANA — YOUON (33) ============ */
  katakana('キャ', 'kya', 2, 5, 'YOUON', 'キャベツ', 'rau bắp cải'),
  katakana('キュ', 'kyu', 2, 5, 'YOUON', 'キュウリ', 'quả dưa chuột'),
  katakana('キョ', 'kyo', 2, 5, 'YOUON', 'トウキョウ', 'thủ đô Tokyo'),
  katakana('シャ', 'sha', 3, 5, 'YOUON', 'シャツ', 'áo sơ mi'),
  katakana('シュ', 'shu', 3, 5, 'YOUON', 'シューズ', 'đôi giày'),
  katakana('ショ', 'sho', 3, 5, 'YOUON', 'ショッピング', 'việc mua sắm'),
  katakana('チャ', 'cha', 4, 5, 'YOUON', 'チャンス', 'cơ hội'),
  katakana('チュ', 'chu', 4, 5, 'YOUON', 'チューリップ', 'hoa tulip'),
  katakana('チョ', 'cho', 4, 5, 'YOUON', 'チョコ', 'sô-cô-la'),
  katakana('ニャ', 'nya', 5, 4, 'YOUON', 'コニャック', 'rượu cognac'),
  katakana('ニュ', 'nyu', 5, 4, 'YOUON', 'ニュース', 'tin tức'),
  katakana('ニョ', 'nyo', 5, 4, 'YOUON', 'ニョロニョロ', 'trườn ngoằn ngoèo'),
  katakana('ヒャ', 'hya', 6, 4, 'YOUON', 'ヒャク', 'một trăm'),
  katakana('ヒュ', 'hyu', 6, 4, 'YOUON', 'ヒューマン', 'con người (human)'),
  katakana('ヒョ', 'hyo', 6, 4, 'YOUON', 'ヒョウタン', 'quả bầu'),
  katakana('ミャ', 'mya', 7, 5, 'YOUON', 'ミャンマー', 'nước Myanmar'),
  katakana('ミュ', 'myu', 7, 5, 'YOUON', 'ミュージック', 'âm nhạc'),
  katakana('ミョ', 'myo', 7, 5, 'YOUON', 'ミョウガ', 'rau gừng Nhật'),
  katakana('リャ', 'rya', 9, 4, 'YOUON', 'コリャ', 'cái này (nói gọn của これは)'),
  katakana('リュ', 'ryu', 9, 4, 'YOUON', 'リュック', 'ba lô'),
  katakana('リョ', 'ryo', 9, 4, 'YOUON', 'リョウリ', 'món ăn, việc nấu nướng'),
  katakana('ギャ', 'gya', 2, 7, 'YOUON', 'ギャグ', 'câu đùa hài'),
  katakana('ギュ', 'gyu', 2, 7, 'YOUON', 'ギュウニュウ', 'sữa bò'),
  katakana('ギョ', 'gyo', 2, 7, 'YOUON', 'ギョーザ', 'bánh xếp gyōza'),
  katakana('ジャ', 'ja', 3, 7, 'YOUON', 'ジャズ', 'nhạc jazz'),
  katakana('ジュ', 'ju', 3, 7, 'YOUON', 'ジュース', 'nước ép trái cây'),
  katakana('ジョ', 'jo', 3, 7, 'YOUON', 'ジョギング', 'việc chạy bộ'),
  katakana('ビャ', 'bya', 6, 6, 'YOUON', 'サンビャク', 'ba trăm'),
  katakana('ビュ', 'byu', 6, 6, 'YOUON', 'デビュー', 'buổi ra mắt đầu tiên'),
  katakana('ビョ', 'byo', 6, 6, 'YOUON', 'ビョーン', 'bay vút đi (từ tượng thanh)'),
  katakana('ピャ', 'pya', 6, 5, 'YOUON', 'ハッピャク', 'tám trăm'),
  katakana('ピュ', 'pyu', 6, 5, 'YOUON', 'ピュア', 'thuần khiết'),
  katakana('ピョ', 'pyo', 6, 5, 'YOUON', 'ピョンピョン', 'nhảy tưng tưng'),
]
