/**
 * NihongoGo — Kanji mở rộng batch 2 (nội dung gốc).
 * 39 chữ N5/N5+ phục vụ các bài L11+ (tham chiếu từ curriculum/lesson11+):
 * 出向越事者例様病夢親兄弟教習開閉壊御申貴参致承顔目声理由予可能確秋冬昔昨頃若疲
 * Quy ước kunyomi: dấu chấm (.) ngăn phần gán cho kanji và okurigana (vd で.る);
 * đọc kun không kèm okurigana thì ghi nguyên (vd こと, もの, ゆめ).
 * JLPT: gán 5 cho chữ xuất hiện trong từ vựng N5 (出, 事, 兄, 弟, 教, 目, 秋, 冬, 昨), còn lại 4.
 */
import type { SeedKanji } from './types'

export const kanjiExtra2: SeedKanji[] = [
  {
    character: '出',
    meaningVi: 'ra, đi ra',
    onyomi: ['シュツ'],
    kunyomi: ['で.る', 'だ.す'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['凵'],
    examples: [
      { word: '出口', reading: 'でぐち', meaningVi: 'lối ra, cửa ra' },
      { word: '出発', reading: 'しゅっぱつ', meaningVi: 'khởi hành' },
      { word: '出席', reading: 'しゅっせき', meaningVi: 'điểm danh, có mặt' },
    ],
    mnemonicVi: 'Chồi non mọc xuyên lên khỏi miệng hố — mọi thứ đang trồi lên, đi RA ngoài (出る, 出す).',
  },
  {
    character: '向',
    meaningVi: 'hướng về',
    onyomi: ['コウ'],
    kunyomi: ['む.かう', 'む.ける', 'む.こう'],
    jlpt: 4,
    strokeCount: 6,
    radicals: ['口'],
    examples: [
      { word: '方向', reading: 'ほうこう', meaningVi: 'hướng, phương hướng' },
      { word: '向かう', reading: 'むかう', meaningVi: 'hướng tới, đi về phía' },
      { word: '向こう', reading: 'むこう', meaningVi: 'bên kia, phía đối diện' },
    ],
    mnemonicVi: 'Cái miệng 口 đặt trong khung nhà 冂, lời nói thẳng một phía — mọi ánh mắt, bước chân đều quay VỀ hướng đó.',
  },
  {
    character: '越',
    meaningVi: 'vượt qua',
    onyomi: ['エツ'],
    kunyomi: ['こ.える', 'こ.す'],
    jlpt: 4,
    strokeCount: 12,
    radicals: ['走'],
    examples: [
      { word: '引っ越し', reading: 'ひっこし', meaningVi: 'việc chuyển nhà' },
      { word: '越える', reading: 'こえる', meaningVi: 'vượt qua (núi, ranh giới)' },
    ],
    mnemonicVi: 'Chân đang 走 (chạy) thì nhảy vọt qua lưỡi rìu lớn — lấy đà hết tốc lực để VƯỢT qua chướng ngại.',
  },
  {
    character: '事',
    meaningVi: 'việc',
    onyomi: ['ジ'],
    kunyomi: ['こと'],
    jlpt: 5,
    strokeCount: 8,
    radicals: ['亅'],
    examples: [
      { word: '仕事', reading: 'しごと', meaningVi: 'công việc' },
      { word: '事故', reading: 'じこ', meaningVi: 'tai nạn' },
      { word: '大事', reading: 'だいじ', meaningVi: 'quan trọng, quý giá' },
    ],
    mnemonicVi: 'Bàn tay nắm chặt sợi dây buộc vào cái móc 亅 — VIỆC gì đã nhận thì phải nắm chắc cho xong.',
  },
  {
    character: '者',
    meaningVi: 'người',
    onyomi: ['シャ'],
    kunyomi: ['もの'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['耂'],
    examples: [
      { word: '医者', reading: 'いしゃ', meaningVi: 'bác sĩ' },
      { word: '患者', reading: 'かんじゃ', meaningVi: 'bệnh nhân' },
      { word: '若者', reading: 'わかもの', meaningVi: 'người trẻ tuổi' },
    ],
    mnemonicVi: 'Ông già 耂 đứng phơi nắng 日 cả buổi — người từng trải; 者 (もの) chỉ chung mọi NGƯỜI.',
  },
  {
    character: '例',
    meaningVi: 'ví dụ',
    onyomi: ['レイ'],
    kunyomi: ['たと.える'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['亻'],
    examples: [
      { word: '例えば', reading: 'たとえば', meaningVi: 'ví dụ như, chẳng hạn' },
      { word: '例文', reading: 'れいぶん', meaningVi: 'câu ví dụ' },
      { word: '例外', reading: 'れいがい', meaningVi: 'ngoại lệ' },
    ],
    mnemonicVi: 'Một người 亻 đứng vào hàng 列 làm mẫu cho mọi người soi — người nêu gương chính là đưa VÍ DỤ.',
  },
  {
    character: '様',
    meaningVi: 'dáng vẻ; đuôi kính ngữ sama',
    onyomi: ['ヨウ'],
    kunyomi: ['さま'],
    jlpt: 4,
    strokeCount: 14,
    radicals: ['木'],
    examples: [
      { word: '皆様', reading: 'みなさま', meaningVi: 'quý vị, mọi người' },
      { word: '様々', reading: 'さまざま', meaningVi: 'đa dạng, đủ kiểu' },
      { word: '神様', reading: 'かみさま', meaningVi: 'vị thần' },
    ],
    mnemonicVi: 'Dưới tán cây 木, chú cừu 羊 nhúng mình xuống dòng nước 水 — dáng vẻ trang nhã nhất, dành cho lời chào lịch sự: 田中様.',
  },
  {
    character: '病',
    meaningVi: 'bệnh, ốm',
    onyomi: ['ビョウ'],
    kunyomi: ['や.む'],
    jlpt: 4,
    strokeCount: 10,
    radicals: ['疒'],
    examples: [
      { word: '病気', reading: 'びょうき', meaningVi: 'bệnh, ốm' },
      { word: '病院', reading: 'びょういん', meaningVi: 'bệnh viện' },
      { word: '病人', reading: 'びょうにん', meaningVi: 'người bệnh' },
    ],
    mnemonicVi: 'Bộ 疒 là chiếc giường nghiêng của người ốm nằm — nhìn thấy bộ này là biết đang BỆNH.',
  },
  {
    character: '夢',
    meaningVi: 'giấc mơ, mơ ước',
    onyomi: ['ム'],
    kunyomi: ['ゆめ'],
    jlpt: 4,
    strokeCount: 13,
    radicals: ['夕'],
    examples: [
      { word: '夢', reading: 'ゆめ', meaningVi: 'giấc mơ, mơ ước' },
      { word: '夢中', reading: 'むちゅう', meaningVi: 'say mê, chìm đắm' },
    ],
    mnemonicVi: 'Đêm 夕 nhắm mắt 罒 ngủ dưới mái nhà, cỏ dại 艹 mọc hoang trong đầu — thức dậy thì thành GIẤC MƠ.',
  },
  {
    character: '親',
    meaningVi: 'cha mẹ; thân thiết',
    onyomi: ['シン'],
    kunyomi: ['おや', 'した.しい', 'した.しむ'],
    jlpt: 4,
    strokeCount: 16,
    radicals: ['見', '木', '立'],
    examples: [
      { word: '両親', reading: 'りょうしん', meaningVi: 'cha mẹ (hai đấng sinh thành)' },
      { word: '父親', reading: 'ちちおや', meaningVi: 'người cha' },
      { word: '親切', reading: 'しんせつ', meaningVi: 'tử tế, tốt bụng' },
    ],
    mnemonicVi: 'Cây 木 mọc thẳng 立 bên hiên nhà, người thân đứng 見 canh giữ — cha mẹ là người luôn ĐẾN GẦN con (親しい).',
  },
  {
    character: '兄',
    meaningVi: 'anh trai',
    onyomi: ['キョウ', 'ケイ'],
    kunyomi: ['あに'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['儿', '口'],
    examples: [
      { word: '兄', reading: 'あに', meaningVi: 'anh trai (nói về anh mình)' },
      { word: 'お兄さん', reading: 'おにいさん', meaningVi: 'anh trai (cách nói lịch sự)' },
      { word: 'お兄ちゃん', reading: 'おにいちゃん', meaningVi: 'anh ơi (cách nói thân mật)' },
    ],
    mnemonicVi: 'Đứa em ngước lên kêu to 「あにー!」: cái miệng 口 lớn giọng nằm trên đôi chân dài 儿 — ANH cao hơn em một cái đầu.',
  },
  {
    character: '弟',
    meaningVi: 'em trai',
    onyomi: ['テイ', 'ダイ'],
    kunyomi: ['おとうと', 'で'],
    jlpt: 5,
    strokeCount: 7,
    radicals: ['弓'],
    examples: [
      { word: '弟', reading: 'おとうと', meaningVi: 'em trai (nói về em mình)' },
      { word: '兄弟', reading: 'きょうだい', meaningVi: 'anh em' },
      { word: '弟子', reading: 'でし', meaningVi: 'trò, đệ tử' },
    ],
    mnemonicVi: 'Đứa EM cầm cây cung 弓 đeo chéo vai, chạy lon ton theo sau lưng anh — nhỏ nhất nhà nên luôn đi sau.',
  },
  {
    character: '教',
    meaningVi: 'dạy, chỉ dạy',
    onyomi: ['キョウ'],
    kunyomi: ['おし.える', 'おそ.わる'],
    jlpt: 5,
    strokeCount: 11,
    radicals: ['攵', '子'],
    examples: [
      { word: '教室', reading: 'きょうしつ', meaningVi: 'lớp học, phòng học' },
      { word: '教える', reading: 'おしえる', meaningVi: 'dạy, chỉ cho' },
      { word: '教科書', reading: 'きょうかしょ', meaningVi: 'sách giáo khoa' },
    ],
    mnemonicVi: 'Thầy cầm thước kẻ 攵 gõ bảng vẽ hình 爻, dạy đứa bé 子 ngồi dưới — nhìn hình là hiểu chữ 教 là DẠY.',
  },
  {
    character: '習',
    meaningVi: 'học, luyện tập',
    onyomi: ['シュウ'],
    kunyomi: ['なら.う'],
    jlpt: 4,
    strokeCount: 11,
    radicals: ['羽', '白'],
    examples: [
      { word: '練習', reading: 'れんしゅう', meaningVi: 'luyện tập' },
      { word: '習慣', reading: 'しゅうかん', meaningVi: 'thói quen' },
      { word: '習う', reading: 'ならう', meaningVi: 'học (môn kỹ năng, năng khiếu)' },
    ],
    mnemonicVi: 'Chú chim vỗ đôi cánh 羽 tập bay từ sáng 白 sớm — HỌC hành phải siêng năng như chim tập bay.',
  },
  {
    character: '開',
    meaningVi: 'mở',
    onyomi: ['カイ'],
    kunyomi: ['ひら.く', 'あ.く'],
    jlpt: 4,
    strokeCount: 12,
    radicals: ['門'],
    examples: [
      { word: '開ける', reading: 'あける', meaningVi: 'mở (cửa, hộp)' },
      { word: '開く', reading: 'あく', meaningVi: 'mở (tự mở ra)' },
      { word: '開始', reading: 'かいし', meaningVi: 'bắt đầu' },
    ],
    mnemonicVi: 'Hai cánh cổng 門 được đẩy toạt sang hai bên, lối đi mở thông thoáng — 開 là MỞ.',
  },
  {
    character: '閉',
    meaningVi: 'đóng, khép',
    onyomi: ['ヘイ'],
    kunyomi: ['し.める', 'し.まる', 'と.じる'],
    jlpt: 4,
    strokeCount: 11,
    radicals: ['門'],
    examples: [
      { word: '閉める', reading: 'しめる', meaningVi: 'đóng (cửa, nắp)' },
      { word: '閉じる', reading: 'とじる', meaningVi: 'khép lại (sách, mắt, cửa)' },
      { word: '閉店', reading: 'へいてん', meaningVi: 'đóng cửa (cửa hàng)' },
    ],
    mnemonicVi: 'Cánh cổng 門 chèn tấm ván 才 ngang giữa — ĐÓNG sầm lại, gõ bao nhiêu cũng chẳng ai mở.',
  },
  {
    character: '壊',
    meaningVi: 'hỏng, vỡ',
    onyomi: ['カイ'],
    kunyomi: ['こわ.れる', 'こわ.す'],
    jlpt: 4,
    strokeCount: 16,
    radicals: ['土'],
    examples: [
      { word: '壊れる', reading: 'こわれる', meaningVi: 'bị hỏng, bị vỡ' },
      { word: '壊す', reading: 'こわす', meaningVi: 'làm hỏng, phá vỡ' },
    ],
    mnemonicVi: 'Vụn đất 土 văng tung tóe, bên trong lở ra một khoảng trống — 壊 là VỠ, là HỎNG.',
  },
  {
    character: '御',
    meaningVi: 'tiền tố kính ngữ go/on',
    onyomi: ['ゴ', 'ギョ'],
    kunyomi: ['み'],
    jlpt: 4,
    strokeCount: 12,
    radicals: ['彳'],
    examples: [
      { word: '御飯', reading: 'ごはん', meaningVi: 'cơm, bữa ăn' },
      { word: '御礼', reading: 'おれい', meaningVi: 'lời cảm ơn' },
      { word: '御馳走', reading: 'ごちそう', meaningVi: 'bữa thịnh soạn, món ngon' },
    ],
    mnemonicVi: 'Người ta bước những bước nhỏ (彳) tới nơi, cúi đầu dâng vật phẩm lên — thêm 御 (お/ご) trước từ để tỏ lòng KÍNH trọng.',
  },
  {
    character: '申',
    meaningVi: 'thưa, bẩm (kính)',
    onyomi: ['シン'],
    kunyomi: ['もう.す'],
    jlpt: 4,
    strokeCount: 5,
    radicals: ['田'],
    examples: [
      { word: '申請', reading: 'しんせい', meaningVi: 'nộp đơn, đề nghị chính thức' },
      { word: '申込', reading: 'もうしこみ', meaningVi: 'việc đăng ký, ứng tuyển' },
      { word: '申す', reading: 'もうす', meaningVi: 'thưa, bẩm (kính ngữ: tôi là…)' },
    ],
    mnemonicVi: 'Tia sét xuyên ngang ruộng 田, phóng thẳng lên trời — 「田中と申します」, lời THƯA như tia chớp xuyên tới.',
  },
  {
    character: '貴',
    meaningVi: 'quý giá',
    onyomi: ['キ'],
    kunyomi: ['とうと.い', 'たっと.い'],
    jlpt: 4,
    strokeCount: 12,
    radicals: ['貝'],
    examples: [
      { word: '貴重', reading: 'きちょう', meaningVi: 'quý giá, đáng quý' },
      { word: '貴方', reading: 'あなた', meaningVi: 'anh, chị (văn viết trang trọng)' },
      { word: '貴社', reading: 'きしゃ', meaningVi: 'quý công ty (trong thư tín)' },
    ],
    mnemonicVi: 'Viên ngọc trong vỏ sò 貝 được đặt lên kệ cao giữa nhà — của QUÝ phải cất cao cho tay thường khó với tới.',
  },
  {
    character: '参',
    meaningVi: 'tham gia; đến (kính)',
    onyomi: ['サン'],
    kunyomi: ['まい.る'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['厶', '大', '彡'],
    examples: [
      { word: '参加', reading: 'さんか', meaningVi: 'sự tham gia' },
      { word: '参考', reading: 'さんこう', meaningVi: 'sự tham khảo' },
      { word: '参る', reading: 'まいる', meaningVi: 'đi, đến (kính ngữ)' },
    ],
    mnemonicVi: 'Người 大 khom lưng chắp tay, ba vệt 彡 mồ hôi rịn má — vất vả lắm mới THAM GIA được cuộc thi.',
  },
  {
    character: '致',
    meaningVi: 'dâng; làm (kính)',
    onyomi: ['チ'],
    kunyomi: ['いた.す'],
    jlpt: 4,
    strokeCount: 10,
    radicals: ['至', '攵'],
    examples: [
      { word: '致す', reading: 'いたす', meaningVi: 'làm (kính ngữ: いたします)' },
      { word: '一致', reading: 'いっち', meaningVi: 'sự nhất quán, trùng khớp' },
    ],
    mnemonicVi: 'Chân đã TỚI (至) nơi, hai tay chắp lại hành lễ (攵) — dâng trọn tấm lòng: よろしくお願い致します.',
  },
  {
    character: '承',
    meaningVi: 'nhận, chấp nhận',
    onyomi: ['ショウ'],
    kunyomi: ['うけたまわ.る'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['手'],
    examples: [
      { word: '承知', reading: 'しょうち', meaningVi: 'hiểu và đồng ý' },
      { word: '承認', reading: 'しょうにん', meaningVi: 'sự phê duyệt, công nhận' },
      { word: '承る', reading: 'うけたまわる', meaningVi: 'tiếp nhận, được nghe (kính ngữ)' },
    ],
    mnemonicVi: 'Hai tay nâng khay, đặt trân trọng vào lòng bàn tay 手 — cung kính NHẬN lệnh: 承知しました.',
  },
  {
    character: '顔',
    meaningVi: 'khuôn mặt',
    onyomi: ['ガン'],
    kunyomi: ['かお'],
    jlpt: 4,
    strokeCount: 15,
    radicals: ['頁'],
    examples: [
      { word: '顔', reading: 'かお', meaningVi: 'khuôn mặt' },
      { word: '笑顔', reading: 'えがお', meaningVi: 'nụ cười' },
      { word: '顔色', reading: 'かおいろ', meaningVi: 'sắc mặt, vẻ mặt' },
    ],
    mnemonicVi: 'Bên trái chàng trai 彦 đang trang điểm, bên phải là chiếc đầu 頁 — chàng nào cũng chăm chút KHUÔN MẶT trước buổi hẹn.',
  },
  {
    character: '目',
    meaningVi: 'mắt',
    onyomi: ['モク', 'ボク'],
    kunyomi: ['め'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['目'],
    examples: [
      { word: '目', reading: 'め', meaningVi: 'con mắt' },
      { word: '目的', reading: 'もくてき', meaningVi: 'mục đích' },
      { word: '目次', reading: 'もくじ', meaningVi: 'mục lục' },
    ],
    mnemonicVi: 'Hình chữ nhật dựng thẳng, chia đôi làm đồng tử — 目 vẽ đúng con MẮT nhìn thẳng.',
  },
  {
    character: '声',
    meaningVi: 'giọng, tiếng',
    onyomi: ['セイ'],
    kunyomi: ['こえ'],
    jlpt: 4,
    strokeCount: 7,
    radicals: ['士'],
    examples: [
      { word: '声', reading: 'こえ', meaningVi: 'giọng nói, tiếng' },
      { word: '大声', reading: 'おおごえ', meaningVi: 'giọng to, quát to' },
      { word: '小声', reading: 'こごえ', meaningVi: 'giọng nhỏ, thì thầm' },
    ],
    mnemonicVi: 'Anh lính 士 đứng sau bục phát thanh — hắng giọng cất TIẾNG hùng hồn vang xa.',
  },
  {
    character: '理',
    meaningVi: 'lý lẽ, đạo lý',
    onyomi: ['リ'],
    kunyomi: [],
    jlpt: 4,
    strokeCount: 11,
    radicals: ['王'],
    examples: [
      { word: '理由', reading: 'りゆう', meaningVi: 'lý do' },
      { word: '無理', reading: 'むり', meaningVi: 'vô lý, quá sức' },
      { word: '整理', reading: 'せいり', meaningVi: 'sự sắp xếp, dọn dẹp' },
    ],
    mnemonicVi: 'Vua 王 khoan mài viên ngọc cho thẳng thớm — việc gì cũng phải mài theo lẽ phải: 理 là LÝ, là phép tắc.',
  },
  {
    character: '由',
    meaningVi: 'lý do, nguyên do',
    onyomi: ['ユ', 'ユウ'],
    kunyomi: ['よし'],
    jlpt: 4,
    strokeCount: 5,
    radicals: ['田'],
    examples: [
      { word: '自由', reading: 'じゆう', meaningVi: 'tự do' },
      { word: '理由', reading: 'りゆう', meaningVi: 'lý do' },
      { word: '経由', reading: 'けいゆ', meaningVi: 'đi qua, qua (trạm, ga)' },
    ],
    mnemonicVi: 'Mầm non trồi lên khỏi mặt ruộng 田 — mọi LÝ DO đều phải mọc ra từ một cái gốc.',
  },
  {
    character: '予',
    meaningVi: 'trước, dự liệu',
    onyomi: ['ヨ'],
    kunyomi: ['あらかじ.め'],
    jlpt: 4,
    strokeCount: 4,
    radicals: ['亅'],
    examples: [
      { word: '予定', reading: 'よてい', meaningVi: 'dự định, lịch hẹn' },
      { word: '予習', reading: 'よしゅう', meaningVi: 'học trước bài' },
      { word: '予報', reading: 'よほう', meaningVi: 'bản dự báo (thời tiết)' },
    ],
    mnemonicVi: 'Đã thấy cái kết 了 nhò mờ từ phía đầu — mọi chuyện tính TRƯỚC: 予定, 予習, 予報.',
  },
  {
    character: '可',
    meaningVi: 'có thể, được',
    onyomi: ['カ'],
    kunyomi: [],
    jlpt: 4,
    strokeCount: 5,
    radicals: ['口'],
    examples: [
      { word: '可能', reading: 'かのう', meaningVi: 'có thể, khả thi' },
      { word: '許可', reading: 'きょか', meaningVi: 'sự cho phép' },
      { word: '可愛い', reading: 'かわいい', meaningVi: 'dễ thương' },
    ],
    mnemonicVi: 'Ông 丁 hé miệng 口 gật gù — phán một tiếng 「ĐƯỢC!」: 可 là được phép, là có thể.',
  },
  {
    character: '能',
    meaningVi: 'năng lực',
    onyomi: ['ノウ'],
    kunyomi: [],
    jlpt: 4,
    strokeCount: 10,
    radicals: ['月'],
    examples: [
      { word: '能力', reading: 'のうりょく', meaningVi: 'năng lực, khả năng' },
      { word: '可能', reading: 'かのう', meaningVi: 'có thể, khả thi' },
    ],
    mnemonicVi: 'Chữ 能 ngày xưa vẽ hình con gấu — con gấu leo cột hái mật, giỏi mọi thứ: đúng chất tài NĂNG của muôn thú.',
  },
  {
    character: '確',
    meaningVi: 'chắc chắn, chính xác',
    onyomi: ['カク'],
    kunyomi: ['たし.か'],
    jlpt: 4,
    strokeCount: 15,
    radicals: ['石'],
    examples: [
      { word: '確か', reading: 'たしか', meaningVi: 'chắc chắn, đáng tin' },
      { word: '確認', reading: 'かくにん', meaningVi: 'sự xác nhận' },
      { word: '正確', reading: 'せいかく', meaningVi: 'chính xác' },
    ],
    mnemonicVi: 'Điều đã khắc lên bia đá 石 thì chẳng bao giờ nhò — CHẮC CHẮN như đá, hãy 確認 trước khi nộp bài.',
  },
  {
    character: '秋',
    meaningVi: 'mùa thu',
    onyomi: ['シュウ'],
    kunyomi: ['あき'],
    jlpt: 5,
    strokeCount: 9,
    radicals: ['禾', '火'],
    examples: [
      { word: '秋', reading: 'あき', meaningVi: 'mùa thu' },
      { word: '秋風', reading: 'あきかぜ', meaningVi: 'gió thu' },
    ],
    mnemonicVi: 'Lúa chín 禾 vàng ươm, đống lá khô bùng cháy 火 — khói thơm báo mùa THU đến, đồng làng đốt lá.',
  },
  {
    character: '冬',
    meaningVi: 'mùa đông',
    onyomi: ['トウ'],
    kunyomi: ['ふゆ'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['冫'],
    examples: [
      { word: '冬', reading: 'ふゆ', meaningVi: 'mùa đông' },
      { word: '冬休み', reading: 'ふゆやすみ', meaningVi: 'kỳ nghỉ đông' },
      { word: '真冬', reading: 'まふゆ', meaningVi: 'giữa đông, lúc rét đậm' },
    ],
    mnemonicVi: 'Hai giọt băng 冫 rơi dài dưới bước chân co rúm 夂 — co ro kéo bước qua mùa ĐÔNG.',
  },
  {
    character: '昔',
    meaningVi: 'ngày xưa, thuở trước',
    onyomi: ['セキ', 'シャク'],
    kunyomi: ['むかし'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['日'],
    examples: [
      { word: '昔', reading: 'むかし', meaningVi: 'ngày xưa, thuở trước' },
      { word: '昔話', reading: 'むかしばなし', meaningVi: 'truyện cổ tích, chuyện ngày xưa' },
      { word: '大昔', reading: 'おおむかし', meaningVi: 'thời xa xưa nhất' },
    ],
    mnemonicVi: 'Hai mươi (廿) lần nắng chồng chất lên mặt trời 日 — đếm hoài mới hay đã NGÀY XƯA mất rồi.',
  },
  {
    character: '昨',
    meaningVi: 'hôm qua, quá khứ',
    onyomi: ['サク'],
    kunyomi: [],
    jlpt: 5,
    strokeCount: 9,
    radicals: ['日'],
    examples: [
      { word: '昨日', reading: 'きのう', meaningVi: 'hôm qua' },
      { word: '一昨日', reading: 'おととい', meaningVi: 'hôm kia' },
      { word: '昨年', reading: 'さくねん', meaningVi: 'năm ngoái' },
    ],
    mnemonicVi: 'Nắng 日 hôm trước chợt 乍 lóe rồi tắt — tưởng vừa mới hôm qua, mà 昨日 đã lùi xa.',
  },
  {
    character: '頃',
    meaningVi: 'khoảng (thời điểm)',
    onyomi: ['ケイ'],
    kunyomi: ['ころ'],
    jlpt: 4,
    strokeCount: 11,
    radicals: ['頁', '匕'],
    examples: [
      { word: '頃', reading: 'ころ', meaningVi: 'lúc, khoảng thời gian' },
      { word: 'この頃', reading: 'このごろ', meaningVi: 'dạo này, gần đây' },
    ],
    mnemonicVi: 'Dao 匕 khẽ tựa lên mái đầu 頁 — ngồi lùi về quá khứ mà ngẫm: "KHOẢNG chừng dạo đó…".',
  },
  {
    character: '若',
    meaningVi: 'trẻ',
    onyomi: ['ジャク'],
    kunyomi: ['わか.い', 'もし'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['艹', '口'],
    examples: [
      { word: '若い', reading: 'わかい', meaningVi: 'trẻ, trẻ tuổi' },
      { word: '若者', reading: 'わかもの', meaningVi: 'người trẻ tuổi' },
    ],
    mnemonicVi: 'Cỏ non 艹 nghiêng mình về bên phải 右 theo gió — cỏ nào cũng chỉ tươi xanh nhất lúc còn TRẺ.',
  },
  {
    character: '疲',
    meaningVi: 'mệt',
    onyomi: ['ヒ'],
    kunyomi: ['つか.れる'],
    jlpt: 4,
    strokeCount: 10,
    radicals: ['疒'],
    examples: [
      { word: '疲れる', reading: 'つかれる', meaningVi: 'mệt, kiệt sức' },
      { word: '疲労', reading: 'ひろう', meaningVi: 'sự mệt mỏi' },
    ],
    mnemonicVi: 'Da dẻ 皮 tái xanh nằm bẹp trên giường 疒 — chạy marathon về tới nhà thì MỆT rã rời.',
  },
]
