/**
 * NihongoGo — Kanji mở rộng batch 1 (nội dung gốc).
 */
import type { SeedKanji } from './types'

export const kanjiExtra1: SeedKanji[] = [
  {
    character: '買',
    meaningVi: 'mua',
    onyomi: ['バイ'],
    kunyomi: ['か.う'],
    jlpt: 5,
    strokeCount: 12,
    radicals: ['罒', '貝'],
    examples: [
      { word: '買う', reading: 'かう', meaningVi: 'mua' },
      { word: '買い物', reading: 'かいもの', meaningVi: 'đi mua sắm' },
      { word: '売買', reading: 'ばいばい', meaningVi: 'việc mua bán' },
    ],
    mnemonicVi: 'Con mắt (罒) nhìn xuống vỏ sò tiền (貝) — ưng món nào là móc ví ra mua món đó.',
  },
  {
    character: '持',
    meaningVi: 'giữ, cầm',
    onyomi: ['ジ'],
    kunyomi: ['も.つ'],
    jlpt: 4,
    strokeCount: 9,
    radicals: ['扌', '寺'],
    examples: [
      { word: '持つ', reading: 'もつ', meaningVi: 'cầm, giữ' },
      { word: '気持ち', reading: 'きもち', meaningVi: 'cảm giác, tâm trạng' },
      { word: 'お金持ち', reading: 'おかねもち', meaningVi: 'người giàu có' },
    ],
    mnemonicVi: 'Đôi tay (扌) nâng bát cơm ở chùa (寺) — nhận bát là phải giữ cho chắc.',
  },
  {
    character: '書',
    meaningVi: 'viết, sách',
    onyomi: ['ショ'],
    kunyomi: ['か.く'],
    jlpt: 5,
    strokeCount: 10,
    radicals: ['日', '聿'],
    examples: [
      { word: '書く', reading: 'かく', meaningVi: 'viết' },
      { word: '辞書', reading: 'じしょ', meaningVi: 'cuốn từ điển' },
      { word: '図書館', reading: 'としょかん', meaningVi: 'thư viện' },
    ],
    mnemonicVi: 'Bàn tay cầm bút (聿) viết say mê suốt ngày (日) — viết xong thành trang sách.',
  },
  {
    character: '読',
    meaningVi: 'đọc',
    onyomi: ['ドク'],
    kunyomi: ['よ.む'],
    jlpt: 5,
    strokeCount: 14,
    radicals: ['言', '売'],
    examples: [
      { word: '読む', reading: 'よむ', meaningVi: 'đọc' },
      { word: '読み方', reading: 'よみかた', meaningVi: 'cách đọc' },
      { word: '読書', reading: 'どくしょ', meaningVi: 'việc đọc sách' },
    ],
    mnemonicVi: 'Người bán sách (売) rao (言) inh ỏi — người qua đường dừng bước giở sách ra đọc.',
  },
  {
    character: '待',
    meaningVi: 'chờ, đợi',
    onyomi: ['タイ'],
    kunyomi: ['ま.つ'],
    jlpt: 4,
    strokeCount: 9,
    radicals: ['彳', '寺'],
    examples: [
      { word: '待つ', reading: 'まつ', meaningVi: 'chờ đợi' },
      { word: '招待', reading: 'しょうたい', meaningVi: 'lời mời' },
      { word: '期待', reading: 'きたい', meaningVi: 'kỳ vọng' },
    ],
    mnemonicVi: 'Bước đi đi lại lại (彳) trước cổng chùa (寺) — đứng sốt ruột chờ người tới.',
  },
  {
    character: '休',
    meaningVi: 'nghỉ ngơi',
    onyomi: ['キュウ'],
    kunyomi: ['やす.む'],
    jlpt: 5,
    strokeCount: 6,
    radicals: ['亻', '木'],
    examples: [
      { word: '休む', reading: 'やすむ', meaningVi: 'nghỉ ngơi' },
      { word: '昼休み', reading: 'ひるやすみ', meaningVi: 'giờ nghỉ trưa' },
      { word: '休日', reading: 'きゅうじつ', meaningVi: 'ngày nghỉ' },
    ],
    mnemonicVi: 'Một người (亻) tựa lưng vào gốc cây (木) — tranh thủ nghỉ mát giữa trưa nắng.',
  },
  {
    character: '働',
    meaningVi: 'làm việc',
    onyomi: ['ドウ'],
    kunyomi: ['はたら.く'],
    jlpt: 4,
    strokeCount: 13,
    radicals: ['亻', '動'],
    examples: [
      { word: '働く', reading: 'はたらく', meaningVi: 'làm việc' },
      { word: '労働', reading: 'ろうどう', meaningVi: 'lao động' },
      { word: '働き', reading: 'はたらき', meaningVi: 'công việc, vai trò' },
    ],
    mnemonicVi: 'Người (亻) kết hợp với sự vận động (動) — lao động chân tay không ngừng nghỉ.',
  },
  {
    character: '入',
    meaningVi: 'vào',
    onyomi: ['ニュウ'],
    kunyomi: ['はい.る', 'い.れる'],
    jlpt: 5,
    strokeCount: 2,
    radicals: ['入'],
    examples: [
      { word: '入る', reading: 'はいる', meaningVi: 'đi vào' },
      { word: '入口', reading: 'いりぐち', meaningVi: 'lối vào' },
      { word: '入学', reading: 'にゅうがく', meaningVi: 'vào trường học' },
    ],
    mnemonicVi: 'Hai nét nhọn chụm lại như mũi tên xuyên vào trong — đồ đi vào là "nhập".',
  },
  {
    character: '立',
    meaningVi: 'đứng',
    onyomi: ['リツ'],
    kunyomi: ['た.つ', 'た.てる'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['立'],
    examples: [
      { word: '立つ', reading: 'たつ', meaningVi: 'đứng dậy' },
      { word: '起立', reading: 'きりつ', meaningVi: 'thế đứng dậy' },
      { word: '国立', reading: 'こくりつ', meaningVi: 'thuộc nhà nước' },
    ],
    mnemonicVi: 'Một người đứng thẳng lưng, chân vững trên mặt đất — dựng đứng vững vàng giữa trời.',
  },
  {
    character: '止',
    meaningVi: 'dừng, ngăn',
    onyomi: ['シ'],
    kunyomi: ['と.まる', 'と.める'],
    jlpt: 4,
    strokeCount: 4,
    radicals: ['止'],
    examples: [
      { word: '止まる', reading: 'とまる', meaningVi: 'dừng lại' },
      { word: '止める', reading: 'とめる', meaningVi: 'dừng (xe) lại' },
      { word: '禁止', reading: 'きんし', meaningVi: 'cấm' },
    ],
    mnemonicVi: 'Bàn chân giậm phanh, ngón cái gác ngang thành vạch — chân chạm vạch là phải dừng.',
  },
  {
    character: '乗',
    meaningVi: 'đi (xe), cưỡi',
    onyomi: ['ジョウ'],
    kunyomi: ['の.る', 'の.せる'],
    jlpt: 4,
    strokeCount: 9,
    radicals: ['禾', '木'],
    examples: [
      { word: '乗る', reading: 'のる', meaningVi: 'lên (xe)' },
      { word: '乗り物', reading: 'のりもの', meaningVi: 'phương tiện giao thông' },
      { word: '乗り換え', reading: 'のりかえ', meaningVi: 'việc đổi tuyến' },
    ],
    mnemonicVi: 'Khung xe gỗ (木) có tay nắm mọc trên cao (禾) — trèo lên là đi được.',
  },
  {
    character: '使',
    meaningVi: 'dùng, sai khiến',
    onyomi: ['シ'],
    kunyomi: ['つか.う'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['亻', '吏'],
    examples: [
      { word: '使う', reading: 'つかう', meaningVi: 'sử dụng' },
      { word: '使い方', reading: 'つかいかた', meaningVi: 'cách sử dụng' },
      { word: '天使', reading: 'てんし', meaningVi: 'thiên thần' },
    ],
    mnemonicVi: 'Người (亻) cầm lệnh bài của quan (吏) — có lệnh trong tay, sai khiến kẻ khác làm việc.',
  },
  {
    character: '忘',
    meaningVi: 'quên',
    onyomi: ['ボウ'],
    kunyomi: ['わす.れる'],
    jlpt: 4,
    strokeCount: 7,
    radicals: ['亡', '心'],
    examples: [
      { word: '忘れる', reading: 'わすれる', meaningVi: 'quên' },
      { word: '忘れ物', reading: 'わすれもの', meaningVi: 'đồ để quên' },
      { word: '忘年会', reading: 'ぼうねんかい', meaningVi: 'tiệc tất niên' },
    ],
    mnemonicVi: 'Trái tim (心) đánh mất (亡) — thứ gì rơi khỏi tim là quên tuốt.',
  },
  {
    character: '帰',
    meaningVi: 'trở về',
    onyomi: ['キ'],
    kunyomi: ['かえ.る', 'かえ.す'],
    jlpt: 4,
    strokeCount: 10,
    radicals: ['巾', '帚'],
    examples: [
      { word: '帰る', reading: 'かえる', meaningVi: 'trở về' },
      { word: '帰り', reading: 'かえり', meaningVi: 'chuyến về nhà' },
      { word: '帰国', reading: 'きこく', meaningVi: 'về nước' },
    ],
    mnemonicVi: 'Cầm chổi (帚) quét dọn nhà cửa xong, cuộn tấm vải (巾) lên đường trở về.',
  },
  {
    character: '起',
    meaningVi: 'thức dậy, nổ ra',
    onyomi: ['キ'],
    kunyomi: ['お.きる', 'お.こす'],
    jlpt: 4,
    strokeCount: 10,
    radicals: ['走', '己'],
    examples: [
      { word: '起きる', reading: 'おきる', meaningVi: 'thức dậy' },
      { word: '起こす', reading: 'おこす', meaningVi: 'đánh thức, gây ra' },
      { word: '早起き', reading: 'はやおき', meaningVi: 'dậy sớm' },
    ],
    mnemonicVi: 'Mình (己) tung mình dậy mà chạy (走) — chuông reo là bật dậy ngay lập tức.',
  },
  {
    character: '寝',
    meaningVi: 'ngủ, nằm',
    onyomi: ['シン'],
    kunyomi: ['ね.る', 'ね.かす'],
    jlpt: 4,
    strokeCount: 13,
    radicals: ['宀', '爿'],
    examples: [
      { word: '寝る', reading: 'ねる', meaningVi: 'ngủ' },
      { word: '寝坊', reading: 'ねぼう', meaningVi: 'dậy muộn' },
      { word: '寝室', reading: 'しんしつ', meaningVi: 'phòng ngủ' },
    ],
    mnemonicVi: 'Dưới mái nhà (宀) kê tấm ván (爿) làm giường — lên giường là ngủ một mạch tới sáng.',
  },
  {
    character: '泳',
    meaningVi: 'bơi',
    onyomi: ['エイ'],
    kunyomi: ['およ.ぐ'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['氵'],
    examples: [
      { word: '泳ぐ', reading: 'およぐ', meaningVi: 'bơi' },
      { word: '水泳', reading: 'すいえい', meaningVi: 'môn bơi' },
      { word: '平泳ぎ', reading: 'ひらおよぎ', meaningVi: 'bơi ếch' },
    ],
    mnemonicVi: 'Nước (氵) bắn tung tóe — người bơi quạt nước mà tiến về phía trước.',
  },
  {
    character: '作',
    meaningVi: 'làm, chế tạo',
    onyomi: ['サク', 'サ'],
    kunyomi: ['つく.る'],
    jlpt: 4,
    strokeCount: 7,
    radicals: ['亻', '乍'],
    examples: [
      { word: '作る', reading: 'つくる', meaningVi: 'làm, nấu' },
      { word: '作文', reading: 'さくぶん', meaningVi: 'bài văn' },
      { word: '作品', reading: 'さくひん', meaningVi: 'tác phẩm' },
    ],
    mnemonicVi: 'Người thợ (亻) gõ búa cạch cạch (乍) — đôi tay làm ra sản phẩm.',
  },
  {
    character: '覚',
    meaningVi: 'ghi nhớ',
    onyomi: ['カク'],
    kunyomi: ['おぼ.える', 'さ.ます'],
    jlpt: 4,
    strokeCount: 12,
    radicals: ['小', '冖', '見'],
    examples: [
      { word: '覚える', reading: 'おぼえる', meaningVi: 'ghi nhớ, học thuộc' },
      { word: '感覚', reading: 'かんかく', meaningVi: 'cảm giác' },
      { word: '目が覚める', reading: 'めがさめる', meaningVi: 'tỉnh giấc' },
    ],
    mnemonicVi: 'Ba giọt mưa nhỏ (小) rơi trên mái che (冖), mắt (見) vẫn dán vào sách — học một lần là ghi nhớ.',
  },
  {
    character: '物',
    meaningVi: 'vật, đồ vật',
    onyomi: ['ブツ', 'モツ'],
    kunyomi: ['もの'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['牜', '勿'],
    examples: [
      { word: '品物', reading: 'しなもの', meaningVi: 'đồ đạc, hàng hóa' },
      { word: '動物', reading: 'どうぶつ', meaningVi: 'động vật' },
      { word: '食べ物', reading: 'たべもの', meaningVi: 'thức ăn' },
    ],
    mnemonicVi: 'Con trâu (牜) gắn cờ hiệu (勿) kéo hàng — trâu xưa là "vật" lực chính của người nông dân.',
  },
  {
    character: '所',
    meaningVi: 'nơi, chỗ',
    onyomi: ['ショ'],
    kunyomi: ['ところ'],
    jlpt: 4,
    strokeCount: 8,
    radicals: ['戸', '斤'],
    examples: [
      { word: '所', reading: 'ところ', meaningVi: 'nơi, chỗ' },
      { word: '住所', reading: 'じゅうしょ', meaningVi: 'địa chỉ' },
      { word: '近所', reading: 'きんじょ', meaningVi: 'khu phố, hàng xóm' },
    ],
    mnemonicVi: 'Cánh cửa (戸) treo cạnh cái búa (斤) — mảnh đất có vạch riêng, là "sở" của mỗi người.',
  },
  {
    character: '思',
    meaningVi: 'nghĩ, suy nghĩ',
    onyomi: ['シ'],
    kunyomi: ['おも.う'],
    jlpt: 4,
    strokeCount: 9,
    radicals: ['田', '心'],
    examples: [
      { word: '思う', reading: 'おもう', meaningVi: 'nghĩ, cho rằng' },
      { word: '思い出', reading: 'おもいで', meaningVi: 'kỷ niệm' },
      { word: '不思議', reading: 'ふしぎ', meaningVi: 'kỳ lạ' },
    ],
    mnemonicVi: 'Thửa ruộng (田) cày trên trái tim (心) — suy nghĩ là làm ruộng trong lồng ngực.',
  },
  {
    character: '言',
    meaningVi: 'nói, lời',
    onyomi: ['ゲン', 'ゴン'],
    kunyomi: ['い.う', 'こと'],
    jlpt: 5,
    strokeCount: 7,
    radicals: ['言'],
    examples: [
      { word: '言う', reading: 'いう', meaningVi: 'nói' },
      { word: '言葉', reading: 'ことば', meaningVi: 'ngôn từ' },
      { word: '方言', reading: 'ほうげん', meaningVi: 'phương ngôn' },
    ],
    mnemonicVi: 'Những vạch gạch ngay trên chiếc miệng — lời từ miệng phát ra thành dòng, ghi lại thành "ngôn".',
  },
  {
    character: '知',
    meaningVi: 'biết',
    onyomi: ['チ'],
    kunyomi: ['し.る'],
    jlpt: 5,
    strokeCount: 8,
    radicals: ['矢', '口'],
    examples: [
      { word: '知る', reading: 'しる', meaningVi: 'biết' },
      { word: '知識', reading: 'ちしき', meaningVi: 'kiến thức' },
      { word: '知り合い', reading: 'しりあい', meaningVi: 'người quen biết' },
    ],
    mnemonicVi: 'Mũi tên (矢) bay thẳng vào miệng (口) — nghe nói một câu là hiểu biết ngay.',
  },
  {
    character: '多',
    meaningVi: 'nhiều',
    onyomi: ['タ'],
    kunyomi: ['おお.い'],
    jlpt: 5,
    strokeCount: 6,
    radicals: ['夕'],
    examples: [
      { word: '多い', reading: 'おおい', meaningVi: 'nhiều' },
      { word: '多分', reading: 'たぶん', meaningVi: 'có lẽ' },
      { word: '多少', reading: 'たしょう', meaningVi: 'nhiều ít' },
    ],
    mnemonicVi: 'Hai buổi chiều (夕) chồng lên nhau — chiều tà kéo dài bất tận, thứ gì cũng thành ra nhiều.',
  },
  {
    character: '少',
    meaningVi: 'ít',
    onyomi: ['ショウ'],
    kunyomi: ['すこ.し', 'すく.ない'],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['小', '丿'],
    examples: [
      { word: '少し', reading: 'すこし', meaningVi: 'một chút' },
      { word: '少ない', reading: 'すくない', meaningVi: 'ít' },
      { word: '少年', reading: 'しょうねん', meaningVi: 'thiếu niên' },
    ],
    mnemonicVi: 'Chữ 小 (nhỏ) khoác thêm một nét chéo — so với "nhiều" thì lại mang tiếng là "ít".',
  },
  {
    character: '同',
    meaningVi: 'cùng, giống nhau',
    onyomi: ['ドウ'],
    kunyomi: ['おな.じ'],
    jlpt: 4,
    strokeCount: 6,
    radicals: ['冂', '口'],
    examples: [
      { word: '同じ', reading: 'おなじ', meaningVi: 'giống nhau' },
      { word: '同時', reading: 'どうじ', meaningVi: 'cùng lúc' },
      { word: '同僚', reading: 'どうりょう', meaningVi: 'đồng nghiệp' },
    ],
    mnemonicVi: 'Chiếc miệng (口) nằm gọn trong khung cửa (冂) — cùng phát ra một âm giống hệt nhau.',
  },
  {
    character: '内',
    meaningVi: 'trong, bên trong',
    onyomi: ['ナイ'],
    kunyomi: ['うち'],
    jlpt: 4,
    strokeCount: 4,
    radicals: ['冂', '入'],
    examples: [
      { word: '内', reading: 'うち', meaningVi: 'trong, nhà' },
      { word: '案内', reading: 'あんない', meaningVi: 'sự hướng dẫn' },
      { word: '国内', reading: 'こくない', meaningVi: 'trong nước' },
    ],
    mnemonicVi: 'Chữ 入 (vào) chui vào giữa khung cửa (冂) — đã chui vào thì ở lại "nội" bên trong.',
  },
  {
    character: '時',
    meaningVi: 'giờ, thời gian',
    onyomi: ['ジ'],
    kunyomi: ['とき'],
    jlpt: 5,
    strokeCount: 10,
    radicals: ['日', '寺'],
    examples: [
      { word: '時間', reading: 'じかん', meaningVi: 'thời gian' },
      { word: '時々', reading: 'ときどき', meaningVi: 'thỉnh thoảng' },
      { word: '何時', reading: 'なんじ', meaningVi: 'mấy giờ' },
    ],
    mnemonicVi: 'Mặt trời (日) soi dấu trên sân chùa (寺) — bóng ngắn dài theo giờ, đất khắc thời gian.',
  },
  {
    character: '朝',
    meaningVi: 'buổi sáng',
    onyomi: ['チョウ'],
    kunyomi: ['あさ'],
    jlpt: 5,
    strokeCount: 12,
    radicals: ['日', '月'],
    examples: [
      { word: '朝', reading: 'あさ', meaningVi: 'buổi sáng' },
      { word: '朝ご飯', reading: 'あさごはん', meaningVi: 'bữa sáng' },
      { word: '毎朝', reading: 'まいあさ', meaningVi: 'mỗi sáng' },
    ],
    mnemonicVi: 'Mặt trời (日) mọc lên giữa cỏ cây, mặt trăng (月) chưa kịp lặn — cảnh buổi sớm mai.',
  },
  {
    character: '夜',
    meaningVi: 'đêm',
    onyomi: ['ヤ'],
    kunyomi: ['よ', 'よる'],
    jlpt: 5,
    strokeCount: 8,
    radicals: ['亠', '人', '夕'],
    examples: [
      { word: '夜', reading: 'よる', meaningVi: 'đêm' },
      { word: '今夜', reading: 'こんや', meaningVi: 'đêm nay' },
      { word: '夜中', reading: 'よなか', meaningVi: 'nửa đêm' },
    ],
    mnemonicVi: 'Dưới mái hiên (亠), người (人) ôm lấy buổi chiều tà (夕) — màn đêm chậm rãi buông xuống.',
  },
  {
    character: '天',
    meaningVi: 'trời',
    onyomi: ['テン'],
    kunyomi: ['あめ'],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['大', '一'],
    examples: [
      { word: '天気', reading: 'てんき', meaningVi: 'thời tiết' },
      { word: '天国', reading: 'てんごく', meaningVi: 'thiên đường' },
      { word: '雨天', reading: 'うてん', meaningVi: 'trời mưa' },
    ],
    mnemonicVi: 'Người (大) dang tay vươn cao thêm một nấc (一) — trên tận đỉnh đầu là trời xanh.',
  },
  {
    character: '気',
    meaningVi: 'không khí, tinh thần',
    onyomi: ['キ'],
    kunyomi: [],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['气'],
    examples: [
      { word: '元気', reading: 'げんき', meaningVi: 'khoẻ khoắn' },
      { word: '電気', reading: 'でんき', meaningVi: 'điện' },
      { word: '空気', reading: 'くうき', meaningVi: 'không khí' },
    ],
    mnemonicVi: 'Hơi nước cuộn thành vòng xoáy (气) — không khí, hơi thở và tinh thần đều là "khí".',
  },
  {
    character: '雨',
    meaningVi: 'mưa',
    onyomi: ['ウ'],
    kunyomi: ['あめ'],
    jlpt: 5,
    strokeCount: 8,
    radicals: ['雨'],
    examples: [
      { word: '雨', reading: 'あめ', meaningVi: 'cơn mưa' },
      { word: '大雨', reading: 'おおあめ', meaningVi: 'mưa lớn' },
      { word: '小雨', reading: 'こさめ', meaningVi: 'mưa phùn' },
    ],
    mnemonicVi: 'Bốn giọt nước rơi rơi từ đám mây — vẽ đúng hình một cơn mưa.',
  },
  {
    character: '毎',
    meaningVi: 'mỗi',
    onyomi: ['マイ'],
    kunyomi: ['ごと'],
    jlpt: 5,
    strokeCount: 6,
    radicals: ['母', '丿'],
    examples: [
      { word: '毎日', reading: 'まいにち', meaningVi: 'mỗi ngày' },
      { word: '毎週', reading: 'まいしゅう', meaningVi: 'mỗi tuần' },
      { word: '毎年', reading: 'まいとし', meaningVi: 'mỗi năm' },
    ],
    mnemonicVi: 'Người mẹ (母) đội chiếc mũ nhọn (丿) — mẹ đều đặn xuất hiện, mỗi ngày một lần.',
  },
  {
    character: '週',
    meaningVi: 'tuần',
    onyomi: ['シュウ'],
    kunyomi: [],
    jlpt: 5,
    strokeCount: 11,
    radicals: ['辶', '周'],
    examples: [
      { word: '週末', reading: 'しゅうまつ', meaningVi: 'cuối tuần' },
      { word: '今週', reading: 'こんしゅう', meaningVi: 'tuần này' },
      { word: '来週', reading: 'らいしゅう', meaningVi: 'tuần sau' },
    ],
    mnemonicVi: 'Vòng tuần hoàn (周) trôi mãi không ngừng (辶) — hết bảy ngày lại quay về một tuần mới.',
  },
  {
    character: '間',
    meaningVi: 'khoảng, giữa',
    onyomi: ['カン', 'ケン'],
    kunyomi: ['あいだ', 'ま'],
    jlpt: 5,
    strokeCount: 12,
    radicals: ['門', '日'],
    examples: [
      { word: '間', reading: 'あいだ', meaningVi: 'khoảng giữa' },
      { word: '人間', reading: 'にんげん', meaningVi: 'con người' },
      { word: '間に合う', reading: 'まにあう', meaningVi: 'kịp giờ' },
    ],
    mnemonicVi: 'Tia nắng (日) lọt qua khe cổng (門) — khoảng "gian" sáng le lói giữa hai cánh cửa.',
  },
  {
    character: '仕',
    meaningVi: 'làm việc, phụng sự',
    onyomi: ['シ'],
    kunyomi: ['つか.える'],
    jlpt: 4,
    strokeCount: 5,
    radicals: ['亻', '士'],
    examples: [
      { word: '仕事', reading: 'しごと', meaningVi: 'công việc' },
      { word: '仕方がない', reading: 'しかたがない', meaningVi: 'không còn cách nào' },
      { word: '仕える', reading: 'つかえる', meaningVi: 'phụng sự, hầu hạ' },
    ],
    mnemonicVi: 'Người (亻) đội mũ học sĩ (士) — người có học đi làm việc tử tế, phụng sự chủ trên.',
  },
  {
    character: '置',
    meaningVi: 'đặt, để',
    onyomi: ['チ'],
    kunyomi: ['お.く'],
    jlpt: 4,
    strokeCount: 13,
    radicals: ['罒', '直'],
    examples: [
      { word: '置く', reading: 'おく', meaningVi: 'đặt, để' },
      { word: '位置', reading: 'いち', meaningVi: 'vị trí' },
      { word: '置き場所', reading: 'おきばしょ', meaningVi: 'chỗ để đồ' },
    ],
    mnemonicVi: 'Cái rổ (罒) đội trên chữ 直 (thẳng) — đặt đồ vào là ngay ngắn, đúng vị trí.',
  },
  {
    character: '終',
    meaningVi: 'kết thúc',
    onyomi: ['シュウ'],
    kunyomi: ['お.わる', 'お.える'],
    jlpt: 4,
    strokeCount: 11,
    radicals: ['糸', '冬'],
    examples: [
      { word: '終わる', reading: 'おわる', meaningVi: 'kết thúc' },
      { word: '終わり', reading: 'おわり', meaningVi: 'phần cuối' },
      { word: '終電', reading: 'しゅうでん', meaningVi: 'chuyến tàu cuối trong ngày' },
    ],
    mnemonicVi: 'Sợi chỉ (糸) quấn qua mùa đông (冬) — ngày cuối cùng của năm, mọi chuyện khép lại.',
  },
]
