/**
 * NihongoGo — Kanji N5 seed data (lõi 40 chữ).
 * File này chứa 40 chữ N5 nền; `kanji-extra1.ts` (+40) và `kanji-extra2.ts` (+39)
 * mở rộng lên tổng 119 chữ (N5 = 68, N4 = 51) — xem `kanjiList` ở cuối file.
 */
import type { SeedKanji } from './types'
import { kanjiExtra1 } from './kanji-extra1'
import { kanjiExtra2 } from './kanji-extra2'

const baseKanjiList: SeedKanji[] = [
  {
    character: '一',
    meaningVi: 'một (số 1)',
    onyomi: ['イチ', 'イツ'],
    kunyomi: ['ひと-つ'],
    jlpt: 5,
    strokeCount: 1,
    radicals: ['一'],
    examples: [
      { word: '一日', reading: 'いちにち', meaningVi: 'một ngày' },
      { word: '一人', reading: 'ひとり', meaningVi: 'một người' },
      { word: '一つ', reading: 'ひとつ', meaningVi: 'một cái' },
    ],
    mnemonicVi: 'Một nét ngang duy nhất — không gì đơn giản hơn con số một.',
  },
  {
    character: '二',
    meaningVi: 'hai (số 2)',
    onyomi: ['ニ'],
    kunyomi: ['ふた-つ'],
    jlpt: 5,
    strokeCount: 2,
    radicals: ['一'],
    examples: [
      { word: '二人', reading: 'ふたり', meaningVi: 'hai người' },
      { word: '二つ', reading: 'ふたつ', meaningVi: 'hai cái' },
      { word: '二日', reading: 'ふつか', meaningVi: 'ngày mùng hai' },
    ],
    mnemonicVi: 'Hai nét ngang xếp chồng lên nhau — cộng thêm một nét là ra hai.',
  },
  {
    character: '三',
    meaningVi: 'ba (số 3)',
    onyomi: ['サン'],
    kunyomi: ['みっ-つ'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['一'],
    examples: [
      { word: '三日', reading: 'みっか', meaningVi: 'ngày mùng ba' },
      { word: '三つ', reading: 'みっつ', meaningVi: 'ba cái' },
      { word: '三人', reading: 'さんにん', meaningVi: 'ba người' },
    ],
    mnemonicVi: 'Ba nét ngang tầng tầng lớp lớp — đếm 1, 2, 3 thật dễ.',
  },
  {
    character: '四',
    meaningVi: 'bốn (số 4)',
    onyomi: ['シ'],
    kunyomi: ['よん', 'よ-つ'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['口'],
    examples: [
      { word: '四日', reading: 'よっか', meaningVi: 'ngày mùng bốn' },
      { word: '四つ', reading: 'よっつ', meaningVi: 'bốn cái' },
      { word: '四季', reading: 'しき', meaningVi: 'bốn mùa' },
    ],
    mnemonicVi: 'Cái 口 (miệng) ôm lấy hai nét nhỏ bên trong — đứa bé bốn tuổi vẫy vùng trong lòng.',
  },
  {
    character: '五',
    meaningVi: 'năm (số 5)',
    onyomi: ['ゴ'],
    kunyomi: ['いつ-つ'],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['二'],
    examples: [
      { word: '五日', reading: 'いつか', meaningVi: 'ngày mùng năm' },
      { word: '五つ', reading: 'いつつ', meaningVi: 'năm cái' },
      { word: '五分', reading: 'ごふん', meaningVi: 'năm phút' },
    ],
    mnemonicVi: 'Hai nét ngang đan xen như bàn tay xòe năm ngón.',
  },
  {
    character: '六',
    meaningVi: 'sáu (số 6)',
    onyomi: ['ロク'],
    kunyomi: ['むっ-つ'],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['八'],
    examples: [
      { word: '六日', reading: 'むいか', meaningVi: 'ngày mùng sáu' },
      { word: '六つ', reading: 'むっつ', meaningVi: 'sáu cái' },
      { word: '六時', reading: 'ろくじ', meaningVi: 'sáu giờ' },
    ],
    mnemonicVi: 'Mái nhà nhỏ đội lên đầu chữ 八 (tám) — số sáu nép mình dưới bóng tám.',
  },
  {
    character: '七',
    meaningVi: 'bảy (số 7)',
    onyomi: ['シチ'],
    kunyomi: ['なな-つ'],
    jlpt: 5,
    strokeCount: 2,
    radicals: ['一'],
    examples: [
      { word: '七日', reading: 'なのか', meaningVi: 'ngày mùng bảy' },
      { word: '七つ', reading: 'ななつ', meaningVi: 'bảy cái' },
      { word: '七時', reading: 'しちじ', meaningVi: 'bảy giờ' },
    ],
    mnemonicVi: 'Chỉ hai nét bắt chéo nhẹ nhàng — nhanh gọn lẹ như chính số bảy.',
  },
  {
    character: '八',
    meaningVi: 'tám (số 8)',
    onyomi: ['ハチ'],
    kunyomi: ['やっ-つ'],
    jlpt: 5,
    strokeCount: 2,
    radicals: ['八'],
    examples: [
      { word: '八日', reading: 'ようか', meaningVi: 'ngày mùng tám' },
      { word: '八つ', reading: 'やっつ', meaningVi: 'tám cái' },
      { word: '八百', reading: 'はっぴゃく', meaningVi: 'tám trăm' },
    ],
    mnemonicVi: 'Hai nét xòe rộng ra như cái kẹp, càng xuống càng to — số tám.',
  },
  {
    character: '九',
    meaningVi: 'chín (số 9)',
    onyomi: ['キュウ', 'ク'],
    kunyomi: ['ここの-つ'],
    jlpt: 5,
    strokeCount: 2,
    radicals: ['乙'],
    examples: [
      { word: '九日', reading: 'ここのか', meaningVi: 'ngày mùng chín' },
      { word: '九つ', reading: 'ここのつ', meaningVi: 'chín cái' },
      { word: '九月', reading: 'くがつ', meaningVi: 'tháng Chín' },
    ],
    mnemonicVi: 'Nét cong cong giống chữ 乙 — cứ bẻ thêm chút nữa là mười, nhưng chưa tới: mới chín thôi.',
  },
  {
    character: '十',
    meaningVi: 'mười (số 10)',
    onyomi: ['ジュウ'],
    kunyomi: ['とお'],
    jlpt: 5,
    strokeCount: 2,
    radicals: ['十'],
    examples: [
      { word: '十日', reading: 'とおか', meaningVi: 'ngày mùng mười' },
      { word: '十人', reading: 'じゅうにん', meaningVi: 'mười người' },
      { word: '十月', reading: 'じゅうがつ', meaningVi: 'tháng Mười' },
    ],
    mnemonicVi: 'Một ngang một dọc giao nhau thành dấu cộng — mười điểm trọn vẹn.',
  },
  {
    character: '百',
    meaningVi: 'trăm (số 100)',
    onyomi: ['ヒャク'],
    kunyomi: [],
    jlpt: 5,
    strokeCount: 6,
    radicals: ['白'],
    examples: [
      { word: '百', reading: 'ひゃく', meaningVi: 'một trăm' },
      { word: '三百', reading: 'さんびゃく', meaningVi: 'ba trăm' },
      { word: '八百', reading: 'はっぴゃく', meaningVi: 'tám trăm' },
    ],
    mnemonicVi: 'Chữ 一 (một) đội đầu chữ 白 (trắng) — "một" ngày trắng trôi qua "trăm" việc.',
  },
  {
    character: '千',
    meaningVi: 'nghìn (số 1.000)',
    onyomi: ['セン'],
    kunyomi: ['ち'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['十'],
    examples: [
      { word: '千', reading: 'せん', meaningVi: 'một nghìn' },
      { word: '三千', reading: 'さんぜん', meaningVi: 'ba nghìn' },
      { word: '千円', reading: 'せんえん', meaningVi: 'một nghìn yên' },
    ],
    mnemonicVi: 'Chữ 十 (mười) thêm một nét phẩy nhỏ — mười nhân mười hóa nghìn.',
  },
  {
    character: '万',
    meaningVi: 'vạn (mười nghìn)',
    onyomi: ['マン', 'バン'],
    kunyomi: [],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['一'],
    examples: [
      { word: '一万', reading: 'いちまん', meaningVi: 'mười nghìn (một vạn)' },
      { word: '万年筆', reading: 'まんねんひつ', meaningVi: 'bút máy' },
      { word: '百万', reading: 'ひゃくまん', meaningVi: 'một triệu (trăm vạn)' },
    ],
    mnemonicVi: 'Một nét ngang bên trên, như chiếc kéo bên dưới — cắt nghìn thành vạn.',
  },
  {
    character: '人',
    meaningVi: 'người',
    onyomi: ['ジン', 'ニン'],
    kunyomi: ['ひと'],
    jlpt: 5,
    strokeCount: 2,
    radicals: ['人'],
    examples: [
      { word: '人', reading: 'ひと', meaningVi: 'con người' },
      { word: '三人', reading: 'さんにん', meaningVi: 'ba người' },
      { word: '日本人', reading: 'にほんじん', meaningVi: 'người Nhật' },
    ],
    mnemonicVi: 'Hai nét nghiêng tựa vào nhau như hai chân người đang sải bước.',
  },
  {
    character: '男',
    meaningVi: 'con trai, đàn ông',
    onyomi: ['ダン', 'ナン'],
    kunyomi: ['おとこ'],
    jlpt: 5,
    strokeCount: 7,
    radicals: ['田', '力'],
    examples: [
      { word: '男', reading: 'おとこ', meaningVi: 'đàn ông, con trai' },
      { word: '男性', reading: 'だんせい', meaningVi: 'nam giới' },
      { word: '男の子', reading: 'おとこのこ', meaningVi: 'bé trai' },
    ],
    mnemonicVi: '田 (ruộng) cộng 力 (sức mạnh) — người đàn ông dồn hết sức lực ra đồng.',
  },
  {
    character: '女',
    meaningVi: 'con gái, phụ nữ',
    onyomi: ['ジョ'],
    kunyomi: ['おんな'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['女'],
    examples: [
      { word: '女', reading: 'おんな', meaningVi: 'phụ nữ, con gái' },
      { word: '女性', reading: 'じょせい', meaningVi: 'nữ giới' },
      { word: '女の子', reading: 'おんなのこ', meaningVi: 'bé gái' },
    ],
    mnemonicVi: 'Người ngồi duyên dáng, hai tay khoanh hờ — dáng vẻ người phụ nữ Nhật.',
  },
  {
    character: '子',
    meaningVi: 'đứa trẻ, con',
    onyomi: ['シ'],
    kunyomi: ['こ'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['子'],
    examples: [
      { word: '子', reading: 'こ', meaningVi: 'đứa trẻ' },
      { word: '子供', reading: 'こども', meaningVi: 'trẻ em' },
      { word: '息子', reading: 'むすこ', meaningVi: 'con trai' },
    ],
    mnemonicVi: 'Đứa trẻ dang hai tay lên trời, đôi chân lúc lắc — tràn đầy sức sống.',
  },
  {
    character: '山',
    meaningVi: 'núi',
    onyomi: ['サン'],
    kunyomi: ['やま'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['山'],
    examples: [
      { word: '山', reading: 'やま', meaningVi: 'ngọn núi' },
      { word: '富士山', reading: 'ふじさん', meaningVi: 'núi Phú Sĩ' },
      { word: '火山', reading: 'かざん', meaningVi: 'núi lửa' },
    ],
    mnemonicVi: 'Ba nét vẽ nên ba đỉnh — đỉnh giữa cao vút nhất.',
  },
  {
    character: '川',
    meaningVi: 'sông, dòng sông',
    onyomi: ['セン'],
    kunyomi: ['かわ'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['川'],
    examples: [
      { word: '川', reading: 'かわ', meaningVi: 'dòng sông' },
      { word: '小川', reading: 'おがわ', meaningVi: 'dòng suối nhỏ' },
      { word: '川辺', reading: 'かわべ', meaningVi: 'bờ sông' },
    ],
    mnemonicVi: 'Ba nét dọc mềm mại như ba dòng nước cùng chảy.',
  },
  {
    character: '田',
    meaningVi: 'ruộng (lúa)',
    onyomi: ['デン'],
    kunyomi: ['た'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['田'],
    examples: [
      { word: '田', reading: 'た', meaningVi: 'cánh đồng, thửa ruộng' },
      { word: '田んぼ', reading: 'たんぼ', meaningVi: 'ruộng lúa' },
      { word: '山田', reading: 'やまだ', meaningVi: 'họ Yamada' },
    ],
    mnemonicVi: 'Vuông vắn chia làm bốn ô — thửa ruộng nhìn từ trên cao xuống.',
  },
  {
    character: '中',
    meaningVi: 'giữa, trong',
    onyomi: ['チュウ'],
    kunyomi: ['なか'],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['口', '丨'],
    examples: [
      { word: '中', reading: 'なか', meaningVi: 'bên trong, ở giữa' },
      { word: '中国', reading: 'ちゅうごく', meaningVi: 'Trung Quốc' },
      { word: '中学', reading: 'ちゅうがく', meaningVi: 'trường trung học cơ sở' },
    ],
    mnemonicVi: 'Một mũi tên xuyên qua giữa cái 口 — đúng trọng tâm, đúng giữa.',
  },
  {
    character: '大',
    meaningVi: 'lớn',
    onyomi: ['ダイ', 'タイ'],
    kunyomi: ['おお-きい'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['大'],
    examples: [
      { word: '大きい', reading: 'おおきい', meaningVi: 'to lớn' },
      { word: '大学', reading: 'だいがく', meaningVi: 'đại học' },
      { word: '大好き', reading: 'だいすき', meaningVi: 'rất thích' },
    ],
    mnemonicVi: 'Người 人 dang rộng hai tay sang hai bên — và trở nên to lớn.',
  },
  {
    character: '小',
    meaningVi: 'nhỏ',
    onyomi: ['ショウ'],
    kunyomi: ['ちい-さい', 'こ'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['小'],
    examples: [
      { word: '小さい', reading: 'ちいさい', meaningVi: 'nhỏ bé' },
      { word: '小鳥', reading: 'ことり', meaningVi: 'chú chim nhỏ' },
      { word: '小学生', reading: 'しょうがくせい', meaningVi: 'học sinh tiểu học' },
    ],
    mnemonicVi: 'Một cái móc nhỏ đứng trên, mọi thứ phía dưới bé lại — nhỏ nhắn xinh xắn.',
  },
  {
    character: '上',
    meaningVi: 'trên, lên',
    onyomi: ['ジョウ'],
    kunyomi: ['うえ', 'あ-がる'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['一', '卜'],
    examples: [
      { word: '上', reading: 'うえ', meaningVi: 'phía trên' },
      { word: '上手', reading: 'じょうず', meaningVi: 'khéo léo, giỏi' },
      { word: '上着', reading: 'うわぎ', meaningVi: 'áo khoác ngoài' },
    ],
    mnemonicVi: 'Chữ 卜 chỉ lên trên đường chân trời 一 — phía trên.',
  },
  {
    character: '下',
    meaningVi: 'dưới, xuống',
    onyomi: ['カ', 'ゲ'],
    kunyomi: ['した', 'さ-がる'],
    jlpt: 5,
    strokeCount: 3,
    radicals: ['一', '卜'],
    examples: [
      { word: '下', reading: 'した', meaningVi: 'phía dưới' },
      { word: '下手', reading: 'へた', meaningVi: 'vụng về' },
      { word: '地下', reading: 'ちか', meaningVi: 'tầng hầm, ngầm' },
    ],
    mnemonicVi: 'Chữ 卜 rơi xuống dưới đường 一 — phía dưới.',
  },
  {
    character: '今',
    meaningVi: 'bây giờ, nay',
    onyomi: ['コン', 'キン'],
    kunyomi: ['いま'],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['人'],
    examples: [
      { word: '今', reading: 'いま', meaningVi: 'bây giờ' },
      { word: '今日', reading: 'きょう', meaningVi: 'hôm nay' },
      { word: '今週', reading: 'こんしゅう', meaningVi: 'tuần này' },
    ],
    mnemonicVi: 'Một nóc nhà 人 che lấy hạt ngôi sao nhỏ — khoảnh khắc đang diễn ra ngay bây giờ.',
  },
  {
    character: '年',
    meaningVi: 'năm',
    onyomi: ['ネン'],
    kunyomi: ['とし'],
    jlpt: 5,
    strokeCount: 6,
    radicals: ['干'],
    examples: [
      { word: '今年', reading: 'ことし', meaningVi: 'năm nay' },
      { word: '去年', reading: 'きょねん', meaningVi: 'năm ngoái' },
      { word: '三年生', reading: 'さんねんせい', meaningVi: 'sinh viên/học sinh năm ba' },
    ],
    mnemonicVi: 'Cây lúa 干 trĩu hạt qua mùa gặt — một năm lại trôi qua.',
  },
  {
    character: '生',
    meaningVi: 'sống, sinh, đời',
    onyomi: ['セイ', 'ショウ'],
    kunyomi: ['い-きる', 'う-まれる'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['生'],
    examples: [
      { word: '先生', reading: 'せんせい', meaningVi: 'thầy cô giáo' },
      { word: '学生', reading: 'がくせい', meaningVi: 'sinh viên' },
      { word: '生きる', reading: 'いきる', meaningVi: 'sống' },
    ],
    mnemonicVi: 'Mầm non vươn lên trên đất, rễ bám sâu — sự sống cứ thế mà lớn.',
  },
  {
    character: '先',
    meaningVi: 'trước, trước tiên',
    onyomi: ['セン'],
    kunyomi: ['さき'],
    jlpt: 5,
    strokeCount: 6,
    radicals: ['牛', '儿'],
    examples: [
      { word: '先生', reading: 'せんせい', meaningVi: 'thầy cô giáo' },
      { word: '先週', reading: 'せんしゅう', meaningVi: 'tuần trước' },
      { word: '先月', reading: 'せんげつ', meaningVi: 'tháng trước' },
    ],
    mnemonicVi: 'Người cầm ngọn cờ phất phơ phía trước, đôi chân chạy nhanh phía sau — kẻ đi đầu.',
  },
  {
    character: '学',
    meaningVi: 'học',
    onyomi: ['ガク'],
    kunyomi: ['まな-ぶ'],
    jlpt: 5,
    strokeCount: 8,
    radicals: ['子'],
    examples: [
      { word: '学生', reading: 'がくせい', meaningVi: 'sinh viên' },
      { word: '大学', reading: 'だいがく', meaningVi: 'đại học' },
      { word: '学ぶ', reading: 'まなぶ', meaningVi: 'học tập' },
    ],
    mnemonicVi: 'Đứa trẻ 子 ngồi dưới mái ấm, hai tay ôm sách — học là chơi, chơi là học.',
  },
  {
    character: '校',
    meaningVi: 'trường học',
    onyomi: ['コウ'],
    kunyomi: [],
    jlpt: 5,
    strokeCount: 10,
    radicals: ['木', '交'],
    examples: [
      { word: '学校', reading: 'がっこう', meaningVi: 'trường học' },
      { word: '高校', reading: 'こうこう', meaningVi: 'trường cấp ba' },
      { word: '校長', reading: 'こうちょう', meaningVi: 'hiệu trưởng' },
    ],
    mnemonicVi: 'Cây 木 đứng cạnh chữ 交 (giao lưu) — nơi trò nhỏ gặp gỡ bạn bè: mái trường.',
  },
  {
    character: '日',
    meaningVi: 'ngày, mặt trời',
    onyomi: ['ニチ', 'ジツ'],
    kunyomi: ['ひ', 'か'],
    jlpt: 5,
    strokeCount: 4,
    radicals: ['日'],
    examples: [
      { word: '日本', reading: 'にほん', meaningVi: 'Nhật Bản' },
      { word: '毎日', reading: 'まいにち', meaningVi: 'mỗi ngày' },
      { word: '日曜日', reading: 'にちようび', meaningVi: 'Chủ nhật' },
    ],
    mnemonicVi: 'Hình một mặt trời tròn với một vạch ngang ở giữa — nguồn gốc của chữ "ngày".',
  },
  {
    character: '本',
    meaningVi: 'gốc, quyển (sách)',
    onyomi: ['ホン'],
    kunyomi: ['もと'],
    jlpt: 5,
    strokeCount: 5,
    radicals: ['木'],
    examples: [
      { word: '日本', reading: 'にほん', meaningVi: 'Nhật Bản' },
      { word: '本屋', reading: 'ほんや', meaningVi: 'hiệu sách' },
      { word: '日本語', reading: 'にほんご', meaningVi: 'tiếng Nhật' },
    ],
    mnemonicVi: 'Gốc cây (木) thêm một gạch ngang ở chân — đánh dấu "gốc" của cây, của sự việc.',
  },
  {
    character: '語',
    meaningVi: 'ngôn ngữ, lời nói',
    onyomi: ['ゴ'],
    kunyomi: ['かたる'],
    jlpt: 5,
    strokeCount: 14,
    radicals: ['言', '口', '五'],
    examples: [
      { word: '日本語', reading: 'にほんご', meaningVi: 'tiếng Nhật' },
      { word: '英語', reading: 'えいご', meaningVi: 'tiếng Anh' },
      { word: '語学', reading: 'ごがく', meaningVi: 'việc học ngoại ngữ' },
    ],
    mnemonicVi: 'Chữ 言 (lời nói) ghép với 五 và 口 (miệng) — năm cái miệng cùng nói một thứ tiếng.',
  },
  {
    character: '話',
    meaningVi: 'câu chuyện, nói chuyện',
    onyomi: ['ワ'],
    kunyomi: ['はなす', 'はなし'],
    jlpt: 5,
    strokeCount: 13,
    radicals: ['言', '舌'],
    examples: [
      { word: '電話', reading: 'でんわ', meaningVi: 'điện thoại' },
      { word: '話す', reading: 'はなす', meaningVi: 'nói' },
      { word: '会話', reading: 'かいわ', meaningVi: 'hội thoại' },
    ],
    mnemonicVi: 'Lời nói (言) trên chiếc lưỡi (舌) — chuyển thành câu chuyện.',
  },
  {
    character: '見',
    meaningVi: 'nhìn, thấy',
    onyomi: ['ケン'],
    kunyomi: ['みる'],
    jlpt: 5,
    strokeCount: 7,
    radicals: ['目', '儿'],
    examples: [
      { word: '見る', reading: 'みる', meaningVi: 'xem' },
      { word: '意見', reading: 'いけん', meaningVi: 'ý kiến' },
      { word: '見学', reading: 'けんがく', meaningVi: 'tham quan học hỏi' },
    ],
    mnemonicVi: 'Con mắt to (目) trên đôi chân (儿) — đi đến chỗ nào cũng nhìn.',
  },
  {
    character: '行',
    meaningVi: 'đi, thực hiện',
    onyomi: ['コウ', 'ギョウ'],
    kunyomi: ['いく', 'おこなう'],
    jlpt: 5,
    strokeCount: 6,
    radicals: ['行'],
    examples: [
      { word: '行く', reading: 'いく', meaningVi: 'đi' },
      { word: '銀行', reading: 'ぎんこう', meaningVi: 'ngân hàng' },
      { word: '旅行', reading: 'りょこう', meaningVi: 'du lịch' },
    ],
    mnemonicVi: 'Hai lối đi song song giao nhau — ngã tư của hành trình.',
  },
  {
    character: '来',
    meaningVi: 'đến, tới',
    onyomi: ['ライ'],
    kunyomi: ['くる'],
    jlpt: 5,
    strokeCount: 7,
    radicals: ['木'],
    examples: [
      { word: '来る', reading: 'くる', meaningVi: 'đến' },
      { word: '来週', reading: 'らいしゅう', meaningVi: 'tuần sau' },
      { word: '来年', reading: 'らいねん', meaningVi: 'năm sau' },
    ],
    mnemonicVi: 'Cây lớn (木) với người đang bước tới — vị khách sắp đến.',
  },
  {
    character: '食',
    meaningVi: 'ăn',
    onyomi: ['ショク'],
    kunyomi: ['たべる'],
    jlpt: 5,
    strokeCount: 9,
    radicals: ['食'],
    examples: [
      { word: '食べる', reading: 'たべる', meaningVi: 'ăn' },
      { word: '食事', reading: 'しょくじ', meaningVi: 'bữa ăn' },
      { word: '朝食', reading: 'ちょうしょく', meaningVi: 'bữa sáng' },
    ],
    mnemonicVi: 'Một nồi cơm có nắp che trên bếp lửa — mùi cơm chín báo giờ ăn.',
  },
  {
    character: '飲',
    meaningVi: 'uống',
    onyomi: ['イン'],
    kunyomi: ['のむ'],
    jlpt: 5,
    strokeCount: 12,
    radicals: ['食', '欠'],
    examples: [
      { word: '飲む', reading: 'のむ', meaningVi: 'uống' },
      { word: '飲み物', reading: 'のみもの', meaningVi: 'đồ uống' },
      { word: '飲食', reading: 'いんしょく', meaningVi: 'ăn uống' },
    ],
    mnemonicVi: 'Chữ 食 (đồ ăn) thêm 欠 (hớp lấy) — đưa lên miệng hớp một ngụm.',
  },
]

/** Toàn bộ kanji khả dụng: 40 chữ nền + 79 chữ mở rộng cho Lesson 11–50. */
export const kanjiList: SeedKanji[] = [...baseKanjiList, ...kanjiExtra1, ...kanjiExtra2]
