/**
 * NihongoGo — Khung 47 bài tiếp theo (order 4 -> 50, trạng thái DRAFT).
 * Mỗi skeleton khai báo chủ đề, mục tiêu và các mảng ngữ pháp / từ vựng / kanji
 * để các tác tử sau này điền nội dung chi tiết. Nội dung GỐC do NihongoGo biên soạn.
 */
import type { SeedLesson } from './types'

export const lessonSkeletons: SeedLesson[] = [
  {
    order: 4,
    slug: 'l4-nanji-desu-ka',
    title: '何時ですか — Thời gian & thời điểm',
    titleJa: '何時ですか',
    description:
      'Hỏi và nói giờ cụ thể, các mốc thời gian trong ngày, cùng khoảng thời gian với mẫu から〜まで.',
    learningObjectives: [
      'Hỏi và trả lời giờ phút chính xác',
      'Nói về khoảng thời gian với から〜まで',
      'Gọi tên các ngày trong tuần và thời điểm trong ngày',
    ],
    grammarTopics: ['Cấu trúc ~時です với mốc thời gian', 'Trợ từ から〜まで (từ... đến...)'],
    vocabularyTopics: ['Số đếm và giờ phút', 'Các ngày trong tuần', 'Thời điểm trong ngày'],
    kanjiTopics: [],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 5,
    slug: 'l5-di-chuyen-phuong-tien',
    title: 'Di chuyển & phương tiện — へ・で・と',
    titleJa: '移動と交通手段',
    description: 'Nói về việc đi đâu, bằng phương tiện gì và đi cùng ai với ba trợ từ へ・で・と.',
    learningObjectives: [
      'Dùng へ để nói hướng đi đến nơi chốn',
      'Dùng で để nói phương tiện di chuyển',
      'Dùng と để nói đi cùng ai',
    ],
    grammarTopics: ['Trợ từ へ (hướng đến nơi chốn)', 'Trợ từ で (phương tiện, cách thức)', 'Cụm と (cùng với ai)'],
    vocabularyTopics: ['Phương tiện giao thông', 'Địa điểm công cộng', 'Động từ di chuyển'],
    kanjiTopics: [],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 6,
    slug: 'l6-dong-tu-tan-ngu',
    title: 'Động từ & tân ngữ — を・何',
    titleJa: '動詞と目的語',
    description: 'Bước đầu làm quen động từ và cách đưa tân ngữ vào câu với trợ từ を, kèm từ hỏi 何.',
    learningObjectives: [
      'Nhận diện động từ thể từ điển',
      'Dùng を để đánh dấu tân ngữ',
      'Hỏi "làm gì" bằng 何',
    ],
    grammarTopics: ['Động từ thể từ điển cơ bản', 'Trợ từ を (tân ngữ trực tiếp)', 'Từ nghi vấn 何 (làm gì)'],
    vocabularyTopics: ['Động từ hoạt động thường ngày', 'Đồ ăn và đồ uống', 'Hoạt động giải trí'],
    kanjiTopics: [],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 7,
    slug: 'l7-loi-moi-de-nghi',
    title: 'Lời mời & đề nghị — 〜ませんか・〜ましょう',
    titleJa: '誘いと提案',
    description: 'Mời ai cùng làm gì một cách lịch sự với 〜ませんか và đề nghị cùng hành động với 〜ましょう.',
    learningObjectives: [
      'Mời lịch sự bằng 〜ませんか',
      'Đề nghị cùng làm bằng 〜ましょう',
      'Chấp nhận hoặc từ chối lời mời một cách tự nhiên',
    ],
    grammarTopics: ['〜ませんか (lời mời lịch sự)', '〜ましょう (cùng làm nhé)'],
    vocabularyTopics: ['Hoạt động cuối tuần', 'Mẫu câu chấp nhận và từ chối'],
    kanjiTopics: [],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 8,
    slug: 'l8-tinh-tu-i-na',
    title: 'Tính từ い/な — Miêu tả sự vật',
    titleJa: 'い形容詞・な形容詞',
    description: 'Miêu tả người và sự vật bằng hai nhóm tính từ い và な, ở cả khẳng định lẫn phủ định.',
    learningObjectives: [
      'Phân biệt tính từ い và な',
      'Chia phủ định cho cả hai nhóm tính từ',
      'Nói cảm nhận về đồ vật, món ăn',
    ],
    grammarTopics: ['Tính từ い (khẳng định, phủ định)', 'Tính từ な (khẳng định, phủ định)', 'Trạng từ từ tính từ (〜く・〜に)'],
    vocabularyTopics: ['Tính từ cảm quan', 'Tính từ đánh giá', 'Từ cảm thán thường dùng'],
    kanjiTopics: [],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 9,
    slug: 'l9-su-ton-tai',
    title: 'あります・います — Sự tồn tại',
    titleJa: 'あります・います',
    description: 'Nói về sự tồn tại của đồ vật, người và động vật cùng vị trí của chúng.',
    learningObjectives: [
      'Dùng あります cho đồ vật vô tri',
      'Dùng います cho người và động vật',
      'Nói vị trí bằng các từ chỉ nơi chốn',
    ],
    grammarTopics: ['あります (đồ vật tồn tại)', 'います (người, động vật tồn tại)', 'Cấu trúc N に あります/います'],
    vocabularyTopics: ['Đồ vật trong phòng', 'Con vật thường gặp', 'Từ chỉ vị trí'],
    kanjiTopics: [],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 10,
    slug: 'l10-bo-dem',
    title: 'Bộ đếm — つ・個・本・人',
    titleJa: '助数詞',
    description: 'Đếm đồ vật theo đúng bộ đếm của từng loại và nói số lượng chính xác.',
    learningObjectives: [
      'Đếm đồ vật nói chung bằng つ',
      'Dùng bộ đếm 個 và 本 đúng loại vật',
      'Đếm người bằng 〜人',
    ],
    grammarTopics: ['Bộ đếm つ (đồ vật nói chung)', 'Bộ đếm 個 và 本', 'Bộ đếm người 〜人'],
    vocabularyTopics: ['Số lượng đồ vật', 'Đồ vật hình trụ (chai, bút...)', 'Cách đếm người'],
    kanjiTopics: [],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 11,
    slug: 'l11-thi-qua-khu',
    title: 'Thì quá khứ — Kể lại điều đã xảy ra',
    titleJa: '過去形',
    description: 'Kể về sự việc đã xảy ra bằng thể quá khứ của です và động từ.',
    learningObjectives: [
      'Chia động từ sang ました',
      'Phủ định quá khứ với ませんでした',
      'Kể lại một sự việc đã qua',
    ],
    grammarTopics: ['Thể quá khứ ました', 'Phủ định quá khứ ませんでした', 'Quá khứ của です (でした)'],
    vocabularyTopics: ['Từ kể chuyện quá khứ', 'Sự kiện và kỷ niệm'],
    kanjiTopics: ['Kanji động từ cơ bản (行・来・見・食)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 12,
    slug: 'l12-mong-muon',
    title: 'Mong muốn — 〜たい',
    titleJa: '〜たい',
    description: 'Bày tỏ mong muốn làm việc gì đó bằng mẫu 〜たい.',
    learningObjectives: [
      'Nói mong muốn với 〜たい',
      'Phủ định và quá khứ của 〜たい',
      'Hỏi về mong muốn của người khác',
    ],
    grammarTopics: ['〜たい (muốn làm gì)', 'Phủ định 〜たくないです', 'Quá khứ 〜たかったです'],
    vocabularyTopics: ['Ước mơ và kế hoạch', 'Món ăn và điểm đến yêu thích'],
    kanjiTopics: ['Kanji hoạt động thường ngày (飲・買・持)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 13,
    slug: 'l13-the-te-yeu-cau',
    title: 'Thể て & yêu cầu — 〜てください',
    titleJa: 'て形と依頼',
    description: 'Chia động từ sang thể て và dùng nó để đưa ra yêu cầu lịch sự.',
    learningObjectives: [
      'Chia thể て cho các nhóm động từ',
      'Đưa yêu cầu với 〜てください',
      'Mô tả chuỗi hành động liên tiếp',
    ],
    grammarTopics: ['Quy tắc chia thể て', '〜てください (đề nghị làm)'],
    vocabularyTopics: ['Chỉ dẫn và cách làm', 'Động từ thao tác (mở, đóng, đặt...)'],
    kanjiTopics: ['Kanji học tập (書・読・話)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 14,
    slug: 'l14-tiep-dien',
    title: 'Tiếp diễn — 〜ている',
    titleJa: '〜ている',
    description: 'Nói hành động đang diễn ra và trạng thái kéo dài với 〜ている.',
    learningObjectives: [
      'Diễn tả hành động đang xảy ra',
      'Dùng 〜ている cho trạng thái thường trực',
      'Hỏi ai đang làm gì',
    ],
    grammarTopics: ['〜ている (hành động đang tiếp diễn)', '〜ている (trạng thái còn duy trì)'],
    vocabularyTopics: ['Hoạt động đang diễn ra', 'Trạng thái quần áo, tư thế'],
    kanjiTopics: ['Kanji thời gian biểu (待・休・働)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 15,
    slug: 'l15-cho-phep-cam',
    title: 'Cho phép & cấm — 〜てもいい・〜てはいけない',
    titleJa: '許可と禁止',
    description: 'Xin phép làm gì và nêu điều bị cấm ở trường học, nơi công cộng.',
    learningObjectives: [
      'Xin phép với 〜てもいいですか',
      'Nêu điều cấm với 〜てはいけません',
      'Đọc hiểu nội quy cơ bản',
    ],
    grammarTopics: ['〜てもいいですか (được phép)', '〜てはいけません (bị cấm)'],
    vocabularyTopics: ['Nội quy và quy định', 'Câu hỏi xin phép'],
    kanjiTopics: ['Kanji biển báo & quy tắc (入・立・止)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 16,
    slug: 'l16-the-nai',
    title: 'Thể ない — Phủ định động từ',
    titleJa: 'ない形',
    description: 'Chia và dùng thể ない để nói không làm việc gì.',
    learningObjectives: [
      'Chia động từ sang thể ない',
      'Nhắc đừng làm với 〜ないでください',
      'Nói kinh nghiệm "chưa từng" với 〜たことがありません',
    ],
    grammarTopics: ['Quy tắc chia thể ない', '〜ないでください (đừng làm)'],
    vocabularyTopics: ['Lời nhắc nhở', 'Việc cần tránh'],
    kanjiTopics: ['Kanji công cụ & sử dụng (乗・使・忘)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 17,
    slug: 'l17-nghia-vu',
    title: 'Nghĩa vụ — 〜なければなりません・〜なくてもいい',
    titleJa: '義務と不必要',
    description: 'Nói về việc bắt buộc phải làm và việc không nhất thiết phải làm.',
    learningObjectives: [
      'Diễn đạt nghĩa vụ với 〜なければなりません',
      'Nói "không cần" với 〜なくてもいい',
      'Phân biệt mức độ bắt buộc của từng mẫu câu',
    ],
    grammarTopics: ['〜なければなりません (phải làm)', '〜なくてもいい (không cần cũng được)'],
    vocabularyTopics: ['Việc phải làm', 'Nghĩa vụ hằng ngày'],
    kanjiTopics: ['Kanji sinh hoạt hằng ngày (帰・起・寝)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 18,
    slug: 'l18-the-kha-nang',
    title: 'Thể khả năng — Có thể & không thể',
    titleJa: '可能形',
    description: 'Nói về khả năng làm được việc gì với thể khả năng và ことができます.',
    learningObjectives: [
      'Chia động từ sang thể khả năng',
      'Dùng ことができます',
      'Nói không thể với 〜られません',
    ],
    grammarTopics: ['Quy tắc chia thể khả năng', '〜ことができます (có thể làm)'],
    vocabularyTopics: ['Kỹ năng và tài năng', 'Thể thao và sở thích'],
    kanjiTopics: ['Kanji năng lực đặc biệt (泳・作・覚)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 19,
    slug: 'l19-cau-xac-dinh',
    title: 'Câu xác định — Thể thường + danh từ',
    titleJa: '連体修飾',
    description: 'Dùng mệnh đề động từ, tính từ để xác định chi tiết cho danh từ đứng sau.',
    learningObjectives: [
      'Nối động từ thể thường với danh từ',
      'Dùng tính từ làm định ngữ',
      'Tạo câu mô tả sự vật chi tiết hơn',
    ],
    grammarTopics: ['Động từ thể thường + danh từ', 'Tính từ + danh từ (mở rộng)'],
    vocabularyTopics: ['Từ miêu tả chi tiết', 'Danh từ ghép thông dụng'],
    kanjiTopics: ['Kanji sự vật & nơi chốn (物・人・所)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 20,
    slug: 'l20-suy-nghi-trich-dan',
    title: 'Suy nghĩ & trích dẫn — 〜と思います',
    titleJa: 'と思います',
    description: 'Diễn đạt ý kiến, suy nghĩ của mình và trích dẫn lời người khác.',
    learningObjectives: [
      'Nói ý kiến với 〜と思います',
      'Trích dẫn với 〜と言いました',
      'Diễn đạt suy đoán nhẹ nhàng',
    ],
    grammarTopics: ['〜と思います (tôi nghĩ rằng)', '〜と言いました (nói rằng)'],
    vocabularyTopics: ['Từ diễn đạt ý kiến', 'Từ nối suy luận'],
    kanjiTopics: ['Kanji tư duy & ngôn ngữ (思・言・知)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 21,
    slug: 'l21-doi-chieu-ly-do',
    title: 'Đối chiếu & lý do — 〜が・〜から',
    titleJa: 'が・から',
    description: 'Nối hai vế câu có sự tương phản với が và nêu lý do với から.',
    learningObjectives: [
      'Dùng が để đối chiếu hai sự việc',
      'Nêu lý do với から',
      'Hỏi lý do với どうして',
    ],
    grammarTopics: ['Trợ từ が (tương phản)', '〜から (vì, bởi vì)'],
    vocabularyTopics: ['Từ chỉ cảm xúc', 'Từ hỏi và trình bày lý do'],
    kanjiTopics: ['Kanji số lượng & so sánh (多・少・同)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 22,
    slug: 'l22-cho-nhan',
    title: 'Cho & nhận — あげる・くれる・もらう',
    titleJa: 'あげる・くれる・もらう',
    description: 'Nói về việc cho và nhận theo hướng quan hệ giữa người nói và các bên.',
    learningObjectives: [
      'Dùng あげる khi mình cho người khác',
      'Dùng くれる khi người khác cho mình',
      'Dùng もらう khi mình nhận từ người khác',
    ],
    grammarTopics: ['あげる (cho đi)', 'くれる (người khác cho mình)', 'もらう (được nhận)'],
    vocabularyTopics: ['Quà tặng và dịp tặng quà', 'Lời cảm ơn'],
    kanjiTopics: ['Kanji vị trí & hướng (上・下・内)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 23,
    slug: 'l23-dieu-kien-tara',
    title: 'Điều kiện たら — Nếu... thì...',
    titleJa: 'たら',
    description: 'Đặt điều kiện cho sự việc sẽ xảy ra với mẫu câu たら.',
    learningObjectives: [
      'Chia động từ sang dạng たら',
      'Nói câu điều kiện "nếu... thì..."',
      'Đưa lời dặn dò, tình huống giả định',
    ],
    grammarTopics: ['Cách tạo dạng たら', 'Câu điều kiện 〜たら'],
    vocabularyTopics: ['Tình huống giả định', 'Kết quả và hệ quả'],
    kanjiTopics: ['Kanji thời điểm (時・朝・夜)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 24,
    slug: 'l24-dieu-kien-ba',
    title: 'Điều kiện ば — Nếu... thì...',
    titleJa: 'ば',
    description: 'Điều kiện ば và cách dùng nó để so sánh, đưa ra lời khuyên.',
    learningObjectives: [
      'Chia động từ sang dạng ば',
      'Dùng 〜ば…どうですか để gợi ý',
      'So sánh điều kiện ば và たら',
    ],
    grammarTopics: ['Cách tạo dạng ば', '〜ば…どうですか (gợi ý)'],
    vocabularyTopics: ['Lời khuyên', 'Tình huống so sánh'],
    kanjiTopics: ['Kanji thời tiết (天・気・雨)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 25,
    slug: 'l25-toki-nagara',
    title: 'とき・ながら — Lúc... / vừa... vừa...',
    titleJa: 'とき・ながら',
    description: 'Nói về thời điểm hành động xảy ra với とき và hai hành động song song với ながら.',
    learningObjectives: [
      'Dùng とき đúng thì của động từ',
      'Diễn tả hành động song song với ながら',
      'Kể lại thói quen theo thời điểm',
    ],
    grammarTopics: ['とき (lúc, khi)', '〜ながら (vừa... vừa...)'],
    vocabularyTopics: ['Thói quen hằng ngày', 'Hoạt động song song'],
    kanjiTopics: ['Kanji tần suất (毎・週・間)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 26,
    slug: 'l26-tro-dong-tu-te',
    title: 'Trợ động từ thể て — 〜てしまう・ておく・てみる',
    titleJa: 'て形の補助動詞',
    description: 'Thêm sắc thái hoàn tất, chuẩn bị, thử làm cho câu động từ bằng các trợ động từ đi sau て.',
    learningObjectives: [
      'Dùng 〜てしまう (lỡ làm, làm hẳn)',
      'Dùng 〜ておく (làm trước)',
      'Dùng 〜てみる (thử làm)',
    ],
    grammarTopics: ['〜てしまう (hoàn tất)', '〜ておく (chuẩn bị trước)', '〜てみる (thử làm)'],
    vocabularyTopics: ['Sự cố nhỏ', 'Việc chuẩn bị'],
    kanjiTopics: ['Kanji hoàn thành (仕・置・終)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 27,
    slug: 'l27-te-iku-kuru',
    title: '〜ていく・〜てくる — Chuyển biến theo thời gian',
    titleJa: '〜ていく・〜てくる',
    description: 'Diễn tả sự thay đổi diễn ra về sau (ていく) và diễn ra đến hiện tại (てくる).',
    learningObjectives: [
      'Dùng 〜ていく cho xu hướng phía trước',
      'Dùng 〜てくる cho diễn biến đến nay',
      'Kể về sự thay đổi theo thời gian',
    ],
    grammarTopics: ['〜ていく (tiếp diễn về sau)', '〜てくる (diễn biến đến hiện tại)'],
    vocabularyTopics: ['Sự thay đổi', 'Từ nói về xu hướng'],
    kanjiTopics: ['Kanji chuyển động (出・向・越)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 28,
    slug: 'l28-danh-tu-hoa',
    title: 'Danh từ hóa — こと・の',
    titleJa: 'こと・の',
    description: 'Biến mệnh đề động từ thành danh từ để làm chủ ngữ, tân ngữ cho câu.',
    learningObjectives: [
      'Dùng こと để danh từ hóa động từ',
      'Dùng の khi nhấn cảm nhận trực tiếp',
      'Nói sở thích, trải nghiệm bằng cấu trúc danh từ hóa',
    ],
    grammarTopics: ['こと (danh từ hóa trung tính)', 'の (danh từ hóa mang cảm nhận)'],
    vocabularyTopics: ['Sở thích và trải nghiệm', 'Cấu trúc nói về việc gì đó'],
    kanjiTopics: ['Kanji khái niệm trừu tượng (事・者・例)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 29,
    slug: 'l29-you-ni',
    title: '〜ように — Để mà & cầu mong',
    titleJa: '〜ように',
    description: 'Nói mục đích cần đạt được và điều mong ước với 〜ように.',
    learningObjectives: [
      'Diễn đạt mục đích với 〜ように',
      'Nói lời chúc, cầu mong',
      'Phân biệt 〜ように và 〜ために',
    ],
    grammarTopics: ['〜ように (nhằm để)', '〜ように (cầu mong)'],
    vocabularyTopics: ['Mục tiêu và kế hoạch', 'Lời chúc'],
    kanjiTopics: ['Kanji mong ước & sức khỏe (様・病・夢)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 30,
    slug: 'l30-the-bi-dong',
    title: 'Thể bị động — 受身',
    titleJa: '受身形',
    description: 'Đưa đối tượng chịu tác động làm chủ ngữ với thể bị động.',
    learningObjectives: [
      'Chia động từ sang thể bị động',
      'Dùng bị động để kể sự khó chịu',
      'Nói về người chịu ảnh hưởng',
    ],
    grammarTopics: ['Quy tắc chia thể bị động', 'Bị động chỉ sự gây phiền'],
    vocabularyTopics: ['Tình huống bị ảnh hưởng', 'Cảm xúc tiêu cực'],
    kanjiTopics: ['Kanji gia đình (親・兄・弟)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 31,
    slug: 'l31-the-sai-khien',
    title: 'Thể sai khiến — 使役',
    titleJa: '使役形',
    description: 'Nói việc bắt hoặc cho phép người khác làm gì với thể sai khiến.',
    learningObjectives: [
      'Chia động từ sang thể sai khiến',
      'Phân biệt させる và 〜てもらう',
      'Ra chỉ thị, phân công công việc',
    ],
    grammarTopics: ['Quy tắc chia thể sai khiến', '〜させる (bảo làm, cho phép làm)'],
    vocabularyTopics: ['Chỉ thị và phân công', 'Quan hệ cấp trên cấp dưới'],
    kanjiTopics: ['Kanji dạy & học (教・習・学)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 32,
    slug: 'l32-tu-dong-qua-do',
    title: 'Động từ tự động & quá độ — 自動詞・他動詞',
    titleJa: '自動詞・他動詞',
    description: 'Phân biệt cặp động từ tự động và quá độ để miêu tả chính xác trạng thái và hành động.',
    learningObjectives: [
      'Nhận diện cặp động từ tự động/quá độ',
      'Chọn đúng trợ từ cho từng loại động từ',
      'Miêu tả trạng thái của vật thể',
    ],
    grammarTopics: ['Cặp động từ tự động và quá độ', 'Phân biệt を・が theo loại động từ'],
    vocabularyTopics: ['Cặp động từ thông dụng', 'Trạng thái vật thể'],
    kanjiTopics: ['Kanji tự động & quá độ (開・閉・壊)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 33,
    slug: 'l33-kinh-ngu-ton-trong',
    title: 'Kính ngữ tôn trọng — 尊敬語',
    titleJa: '尊敬語',
    description: 'Nói lịch sự về hành động của người trên, khách hàng với kính ngữ tôn trọng.',
    learningObjectives: [
      'Dùng các động từ tôn trọng thông dụng',
      'Dùng mẫu お〜になる',
      'Giao tiếp lịch sự nơi công sở',
    ],
    grammarTopics: ['Động từ tôn trọng thông dụng', 'Mẫu お〜になる'],
    vocabularyTopics: ['Từ xưng hô lịch sự', 'Giao tiếp nơi công sở'],
    kanjiTopics: ['Kanji kính ngữ (御・申・貴)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 34,
    slug: 'l34-kinh-ngu-khiem-nhuong',
    title: 'Kính ngữ khiêm nhường — 謙譲語',
    titleJa: '謙譲語',
    description: 'Hạ thấp hành động của chính mình để tỏ ra khiêm tốn với người nghe.',
    learningObjectives: [
      'Dùng các động từ khiêm nhường thông dụng',
      'Dùng mẫu お〜する',
      'Giao tiếp với khách hàng',
    ],
    grammarTopics: ['Động từ khiêm nhường thông dụng', 'Mẫu お〜する'],
    vocabularyTopics: ['Giao tiếp khách hàng', 'Lời chào trang trọng'],
    kanjiTopics: ['Kanji khiêm nhường (参・致・承)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 35,
    slug: 'l35-sou-desu',
    title: '〜そうです — Nghe nói & trông có vẻ',
    titleJa: '〜そうです',
    description: 'Dự đoán theo vẻ ngoài và truyền lại thông tin nghe được với hai dạng そうです.',
    learningObjectives: [
      'Dùng そうです khi dự đoán từ vẻ ngoài',
      'Dùng そうです khi truyền lại thông tin nghe được',
      'Phân biệt hai dạng theo cách nối câu',
    ],
    grammarTopics: ['〜そうです (dự đoán từ vẻ ngoài)', '〜そうです (truyền đạt thông tin)'],
    vocabularyTopics: ['Dự đoán từ hình dáng', 'Từ truyền tin'],
    kanjiTopics: ['Kanji ngoại hình & dáng vẻ (顔・目・声)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 36,
    slug: 'l36-hazu-desu',
    title: '〜はずです — Chắc chắn là',
    titleJa: '〜はずです',
    description: 'Suy luận có căn cứ chắc chắn với はずです và dạng phủ định はずがありません.',
    learningObjectives: [
      'Dùng 〜はずです cho suy luận hợp lý',
      'Phủ định với 〜はずがありません',
      'Phân biệt はず và でしょう',
    ],
    grammarTopics: ['〜はずです (chắc chắn là)', '〜はずがありません (không thể nào)'],
    vocabularyTopics: ['Từ suy luận', 'Kỳ vọng và thực tế'],
    kanjiTopics: ['Kanji suy luận & dự kiến (理・由・予)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 37,
    slug: 'l37-kamo-shiremasen',
    title: '〜かもしれません — Có thể là',
    titleJa: '〜かもしれません',
    description: 'Nói về khả năng xảy ra một cách dè dặt với かもしれません.',
    learningObjectives: [
      'Dùng 〜かもしれません cho phỏng đoán',
      'So sánh mức độ với でしょう',
      'Nói dự báo, phỏng đoán tình huống',
    ],
    grammarTopics: ['〜かもしれません (có lẽ)', 'Phân biệt でしょう・かもしれません'],
    vocabularyTopics: ['Dự báo thời tiết', 'Lời phỏng đoán'],
    kanjiTopics: ['Kanji khả năng (可・能・確)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 38,
    slug: 'l38-no-ni',
    title: '〜のに — Mặc dù... nhưng...',
    titleJa: '〜のに',
    description: 'Diễn đạt ý tương phản kèm cảm xúc nuối tiếc với のに.',
    learningObjectives: [
      'Dùng のに nối hai vế trái ngược',
      'Phân biệt のに với が',
      'Diễn tả cảm xúc tiếc nuối',
    ],
    grammarTopics: ['〜のに (tương phản kèm cảm xúc)', 'Phân biệt が・のに'],
    vocabularyTopics: ['Tình huống trái mong đợi', 'Cảm xúc tiếc nuối'],
    kanjiTopics: ['Kanji tương phản (秋・冬・昔)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 39,
    slug: 'l39-bakari',
    title: '〜ばかり — Vừa mới / chỉ toàn',
    titleJa: '〜ばかり',
    description: 'Nói việc vừa mới xảy ra và thói quen chỉ toàn làm một việc với ばかり.',
    learningObjectives: [
      'Dùng 〜たばかり (vừa mới làm)',
      'Dùng 〜ばかり (chỉ mỗi việc đó)',
      'Than phiền nhẹ nhàng về thói quen',
    ],
    grammarTopics: ['〜たばかり (vừa mới)', '〜ばかり (chỉ mỗi việc đó)'],
    vocabularyTopics: ['Sự việc vừa xảy ra', 'Thói quen lặp lại'],
    kanjiTopics: ['Kanji thời điểm gần (今・昨・頃)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 40,
    slug: 'l40-sou-ni-miemasu',
    title: '〜そうに見えます — Nhìn có vẻ',
    titleJa: '〜そうに見えます',
    description: 'Nhận xét về vẻ bề ngoài một cách giữ khoảng cách với 〜そうに見えます.',
    learningObjectives: [
      'Dùng 〜そうに見えます khi nhận xét người khác',
      'Phân biệt với 〜そうです',
      'Miêu tả dáng vẻ bên ngoài',
    ],
    grammarTopics: ['〜そうに見えます (trông có vẻ)', 'Phân biệt そうです (trực tiếp/gián tiếp)'],
    vocabularyTopics: ['Dáng vẻ bề ngoài', 'Từ miêu tả người'],
    kanjiTopics: ['Kanji dáng vẻ (若・年・疲)'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 41,
    slug: 'l41-tong-on-ngu-phap-n5-1',
    title: 'Tổng ôn ngữ pháp N5 — Phần 1',
    titleJa: '文法総復習Ⅰ',
    description: 'Ôn lại toàn bộ trợ từ và các thể động từ nền tảng trong phạm vi N5.',
    learningObjectives: [
      'Ôn trợ từ cơ bản (は・が・を・に・で)',
      'Ôn thể て・ない・quá khứ',
      'Làm bài tập trộn tổng hợp',
    ],
    grammarTopics: ['Ôn trợ từ cơ bản', 'Ôn các thể động từ nền tảng'],
    vocabularyTopics: ['Ôn từ vựng trường học', 'Ôn từ vựng sinh hoạt'],
    kanjiTopics: ['Kanji số & đơn vị (一〜十)', 'Kanji người (人・男・女)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 42,
    slug: 'l42-tong-on-ngu-phap-n5-2',
    title: 'Tổng ôn ngữ pháp N5 — Phần 2',
    titleJa: '文法総復習Ⅱ',
    description: 'Ôn các mẫu câu giao tiếp và kính ngữ cơ bản, chốt lại toàn bộ phạm vi N5.',
    learningObjectives: [
      'Ôn mẫu câu mời, đề nghị, điều kiện',
      'Ôn kính ngữ cơ bản',
      'Tự kiểm tra tổng thể trước khi lên N4',
    ],
    grammarTopics: ['Ôn mẫu câu giao tiếp thông dụng', 'Ôn so sánh và điều kiện'],
    vocabularyTopics: ['Ôn từ vựng giao tiếp', 'Ôn từ vựng thời gian và số'],
    kanjiTopics: ['Kanji thời gian (日・月・年)', 'Kanji phương vị (上・下・中)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 43,
    slug: 'l43-kanji-chuyen-sau-n5',
    title: 'Kanji chuyên sâu N5 — Ký tự, âm đọc & cách viết',
    titleJa: '漢字特訓',
    description: 'Luyện tập sâu về ký tự, âm đọc và cách viết các kanji trong phạm vi N5.',
    learningObjectives: [
      'Nhớ âm On/Kun của kanji N5',
      'Đọc đúng từ vựng kèm kanji',
      'Viết kanji theo đúng số nét',
    ],
    grammarTopics: [],
    vocabularyTopics: ['Từ vựng kèm kanji thông dụng N5'],
    kanjiTopics: ['Kanji thiên nhiên (山・川・空)', 'Kanji cơ thể (手・目・口)', 'Kanji động tác (行・来・見)'],
    difficulty: 'BEGINNER',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 44,
    slug: 'l44-luyen-nghe-giao-tiep',
    title: 'Luyện nghe giao tiếp — Nghe hiểu tình huống thực tế',
    titleJa: '聞き取り練習',
    description: 'Luyện nghe các tình huống giao tiếp ngắn, bám theo tốc độ tự nhiên.',
    learningObjectives: [
      'Nghe hiểu câu hỏi và trả lời nhanh',
      'Nghe chính xác số, giờ, địa điểm',
      'Làm quen tốc độ hội thoại thật',
    ],
    grammarTopics: [],
    vocabularyTopics: ['Mẫu câu giao tiếp nhanh', 'Nghe số và thời gian'],
    kanjiTopics: ['Ôn tập Kanji N5 qua bối cảnh nghe'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 45,
    slug: 'l45-luyen-doc-doan-ngan',
    title: 'Luyện đọc đoạn ngắn — Nắm ý chính & chi tiết',
    titleJa: '読解練習',
    description: 'Đọc các đoạn văn ngắn về đời sống, nắm ý chính và chi tiết quan trọng.',
    learningObjectives: [
      'Nắm ý chính của đoạn văn',
      'Tìm chi tiết theo câu hỏi',
      'Đoán nghĩa từ mới qua ngữ cảnh',
    ],
    grammarTopics: [],
    vocabularyTopics: ['Từ vựng đọc hiểu', 'Từ nối đoạn văn'],
    kanjiTopics: ['Kanji trong đoạn văn ngắn'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 46,
    slug: 'l46-hoi-thoai-thuc-te',
    title: 'Hội thoại thực tế — Giao tiếp tình huống đời thường',
    titleJa: '実践会話',
    description: 'Thực hành hội thoại trong các tình huống đời thường như mua sắm, hỏi đường, ăn uống.',
    learningObjectives: [
      'Thực hành hội thoại theo tình huống',
      'Dùng cách đáp tự nhiên của người Nhật',
      'Phân biệt ngữ điệu lịch sự và thân mật',
    ],
    grammarTopics: [],
    vocabularyTopics: ['Ngôn ngữ đời thường', 'Từ đệm hội thoại'],
    kanjiTopics: ['Kanji giao tiếp thường ngày'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 47,
    slug: 'l47-mo-rong-tu-vung-n5-n4',
    title: 'Mở rộng từ vựng N5→N4 — Làm giàu vốn từ',
    titleJa: '語彙拡張',
    description: 'Bắc cầu sang N4 bằng cách mở rộng từ vựng theo chủ đề và theo nhóm đồng nghĩa, trái nghĩa.',
    learningObjectives: [
      'Mở rộng từ vựng theo chủ đề quen thuộc',
      'Phân biệt các cặp từ dễ nhầm',
      'Chuyển tiếp tự nhiên sang N4',
    ],
    grammarTopics: [],
    vocabularyTopics: ['Từ đồng nghĩa và trái nghĩa', 'Từ vựng N4 theo chủ đề'],
    kanjiTopics: ['Kanji từ vựng chuyển tiếp N4'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 48,
    slug: 'l48-ngu-phap-n4-nen-tang',
    title: 'Ngữ pháp N4 nền tảng — Những mẫu câu đầu tiên của N4',
    titleJa: 'N4文法入門',
    description: 'Làm quen các cấu trúc ghép câu và mẫu chức năng đầu tiên của N4.',
    learningObjectives: [
      'Nhận diện cấu trúc câu ghép N4',
      'Dùng các mẫu chức năng thông dụng',
      'Kết nối với vốn N5 đã có',
    ],
    grammarTopics: ['Tổng quan câu ghép N4', 'Các mẫu câu chức năng đầu tiên'],
    vocabularyTopics: ['Từ vựng học thuật đơn giản'],
    kanjiTopics: ['Kanji ngữ pháp N4 cơ bản'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 49,
    slug: 'l49-thi-thu-tong-hop',
    title: 'Thi thử tổng hợp — Làm quen cấu trúc đề',
    titleJa: '模擬試験',
    description: 'Làm bài thi thử theo cấu trúc đề N5 với đủ phần ngữ pháp, từ vựng, đọc và nghe.',
    learningObjectives: [
      'Làm quen cấu trúc đề thi',
      'Phân bổ thời gian hợp lý',
      'Rà soát lỗ hổng kiến thức',
    ],
    grammarTopics: ['Ôn tổng hợp phạm vi N5', 'Chiến lược làm bài thi'],
    vocabularyTopics: ['Từ vựng thi thử'],
    kanjiTopics: ['Ôn Kanji tổng hợp'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
  {
    order: 50,
    slug: 'l50-tong-ket-so-cap',
    title: 'Tổng kết sơ cấp — Chốt kiến thức, mở lối trung cấp',
    titleJa: '初級総まとめ',
    description: 'Nhìn lại toàn bộ hành trình sơ cấp, chốt kiến thức cốt lõi và định hướng lộ trình trung cấp.',
    learningObjectives: [
      'Tổng ôn kiến thức cốt lõi sơ cấp',
      'Tự đánh giá trình độ hiện tại',
      'Lên kế hoạch học trung cấp',
    ],
    grammarTopics: ['Tổng ôn sơ cấp'],
    vocabularyTopics: ['Từ vựng tổng hợp', 'Ôn tập theo chủ đề'],
    kanjiTopics: ['Tổng ôn Kanji sơ cấp'],
    difficulty: 'ELEMENTARY',
    status: 'DRAFT',
    nodes: [],
    vocabulary: [],
    grammar: [],
  },
]
